include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Existing rules
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    prefer_single_quotes: true

    # Code quality
    annotate_overrides: true
    avoid_empty_else: true
    avoid_unnecessary_containers: true
    empty_statements: true
    no_duplicate_case_values: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    unnecessary_brace_in_string_interps: true
    use_key_in_widget_constructors: true

    # Type safety
    always_declare_return_types: true

    # Style
    sort_child_properties_last: true
    prefer_final_locals: true

analyzer:
  errors:
    # New rules start as warnings to avoid blocking CI
    always_declare_return_types: warning
    prefer_final_locals: info
    sort_child_properties_last: info
    annotate_overrides: info
    use_build_context_synchronously: ignore
    deprecated_member_use: ignore
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
