/// A scheduled celebration event (birthday or milestone).
///
/// Generated by the daily scheduler, sent by the creator via template.
class CelebrationEvent {
  final String id;
  final String channelId;
  final String fanCelebrationId;
  final String
      eventType; // birthday, milestone_50, milestone_100, milestone_365
  final DateTime dueDate;
  final String status; // pending, sent, skipped, expired
  final CelebrationPayload payload;
  final String? messageId;
  final DateTime createdAt;
  final DateTime? sentAt;

  const CelebrationEvent({
    required this.id,
    required this.channelId,
    required this.fanCelebrationId,
    required this.eventType,
    required this.dueDate,
    this.status = 'pending',
    required this.payload,
    this.messageId,
    required this.createdAt,
    this.sentAt,
  });

  factory CelebrationEvent.fromJson(Map<String, dynamic> json) {
    return CelebrationEvent(
      id: json['id'] as String? ?? json['event_id'] as String? ?? '',
      channelId: json['channel_id'] as String? ?? '',
      fanCelebrationId: json['fan_celebration_id'] as String? ?? '',
      eventType: json['event_type'] as String,
      dueDate: json['due_date'] != null
          ? DateTime.parse(json['due_date'] as String)
          : DateTime.now(),
      status: json['status'] as String? ?? 'pending',
      payload: CelebrationPayload.fromJson(
        json['payload'] is Map<String, dynamic>
            ? json['payload'] as Map<String, dynamic>
            : {
                'nickname': json['nickname'] as String? ?? '팬',
                'day_count': json['day_count'],
                'tier': json['tier'] as String? ?? 'BASIC',
              },
      ),
      messageId: json['message_id'] as String?,
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : DateTime.now(),
      sentAt: json['sent_at'] != null
          ? DateTime.parse(json['sent_at'] as String)
          : null,
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'channel_id': channelId,
        'fan_celebration_id': fanCelebrationId,
        'event_type': eventType,
        'due_date': dueDate.toIso8601String().split('T').first,
        'status': status,
        'payload': payload.toJson(),
        'message_id': messageId,
      };

  /// Whether this event is a birthday.
  bool get isBirthday => eventType == 'birthday';

  /// Whether this event is a subscription milestone.
  bool get isMilestone => eventType.startsWith('milestone_');

  /// Korean label for the event type.
  String get eventTypeLabel {
    switch (eventType) {
      case 'birthday':
        return '생일';
      case 'milestone_50':
        return '50일';
      case 'milestone_100':
        return '100일';
      case 'milestone_365':
        return '1주년';
      default:
        return eventType;
    }
  }

  /// Emoji for the event type.
  String get eventTypeEmoji {
    switch (eventType) {
      case 'birthday':
        return '🎂';
      case 'milestone_50':
        return '💝';
      case 'milestone_100':
        return '🎊';
      case 'milestone_365':
        return '🌟';
      default:
        return '🎉';
    }
  }
}

/// Payload attached to a celebration event.
class CelebrationPayload {
  final String nickname;
  final String? userId;
  final int? dayCount;
  final String tier;

  const CelebrationPayload({
    required this.nickname,
    this.userId,
    this.dayCount,
    this.tier = 'BASIC',
  });

  factory CelebrationPayload.fromJson(Map<String, dynamic> json) {
    return CelebrationPayload(
      nickname: json['nickname'] as String? ?? '팬',
      userId: json['user_id'] as String?,
      dayCount: json['day_count'] as int?,
      tier: json['tier'] as String? ?? 'BASIC',
    );
  }

  Map<String, dynamic> toJson() => {
        'nickname': nickname,
        if (userId != null) 'user_id': userId,
        if (dayCount != null) 'day_count': dayCount,
        'tier': tier,
      };
}
