-- =============================================================
-- 023_image_storage_buckets.sql
-- Image Upload를 위한 Supabase Storage 버킷 및 정책 설정
-- =============================================================
-- NOTE: Storage buckets and policies must be created via the
-- Supabase Dashboard or Storage API, not via SQL migrations.
-- The postgres role does not own storage.objects/storage.buckets.
--
-- Required buckets (create via Dashboard):
--   - campaign-images (public, 5MB, image/*)
--   - team-avatars (public, 5MB, image/*)
--   - benefit-images (public, 5MB, image/*)
--   - avatars (public, 5MB, image/*)
--   - media (private, 50MB, image/*, video/*, audio/*)
--   - funding-images (public, 10MB, image/*)
--
-- This migration is a placeholder to maintain migration numbering.
-- Actual storage setup is handled in the deployment script.
SELECT 1;
