-- 031_seed_question_cards.sql
-- 800개 질문 카드 시드 데이터 임포트
-- Generated from content/question_card_deck_800.jsonl

-- 먼저 기존 샘플 카드 삭제 (fingerprint 기준)
DELETE FROM question_cards WHERE fingerprint LIKE 'seed_%';

-- 질문 카드 임포트
INSERT INTO question_cards (deck_id, subdeck, level, language, card_text, tags, fingerprint)
SELECT 
  qd.id as deck_id,
  t.subdeck,
  t.level,
  'ko' as language,
  t.card_text,
  t.tags,
  t.fingerprint
FROM question_decks qd
CROSS JOIN (VALUES
  ('maid', 'icebreaker', 1, '오늘 기분을 날씨로 표현하면?', ARRAY['기분','날씨','가벼운']::text[], 'seed_55a7758e77ebb707'),
  ('maid', 'icebreaker', 1, '지금 마시고 싶은 음료 하나만!', ARRAY['음료','취향','선택']::text[], 'seed_ff11b22937431fe0'),
  ('maid', 'icebreaker', 1, '오늘 출근길에 들은 첫 번째 노래는?', ARRAY['음악','출근','일상']::text[], 'seed_3a20bac30036ba1e'),
  ('maid', 'icebreaker', 1, '지금 신고 있는 신발 색깔은?', ARRAY['패션','디테일','가벼운']::text[], 'seed_1e585deb16924dd8'),
  ('maid', 'icebreaker', 1, '오늘 아침에 일어나서 제일 먼저 한 일은?', ARRAY['아침','루틴','일상']::text[], 'seed_c0b1f9f6489536a0'),
  ('maid', 'icebreaker', 1, '지금 가장 먹고 싶은 간식은?', ARRAY['간식','취향','음식']::text[], 'seed_504621b0405e9fd3'),
  ('maid', 'icebreaker', 1, '오늘 하루를 이모지 하나로 표현하면?', ARRAY['이모지','기분','가벼운']::text[], 'seed_2d04f640a28c206e'),
  ('maid', 'icebreaker', 1, '최근에 본 귀여운 동물 사진이 있다면?', ARRAY['동물','귀여움','일상']::text[], 'seed_fc07be6eefd1fa3a'),
  ('maid', 'icebreaker', 1, '요즘 자주 쓰는 말버릇이 있어?', ARRAY['말버릇','습관','재미']::text[], 'seed_a71489a51d0a425c'),
  ('maid', 'icebreaker', 1, '오늘 손님에게 처음 건넨 인사는 뭐였어?', ARRAY['인사','접객','메이드']::text[], 'seed_df0aabe875116f01'),
  ('maid', 'icebreaker', 1, '지금 머리 스타일은 어떤 느낌?', ARRAY['헤어','패션','외모']::text[], 'seed_f070936ab7fcfec1'),
  ('maid', 'icebreaker', 1, '오늘 입은 앞치마(에이프런) 색깔은?', ARRAY['의상','메이드','디테일']::text[], 'seed_2f74be47511ca520'),
  ('maid', 'icebreaker', 1, '출근 전에 꼭 하는 루틴 하나?', ARRAY['루틴','습관','일상']::text[], 'seed_87bc8c7fa1e39ceb'),
  ('maid', 'icebreaker', 1, '지금 주머니에 뭐가 들어있어?', ARRAY['소지품','디테일','재미']::text[], 'seed_863550ac87b1095a'),
  ('maid', 'icebreaker', 1, '오늘 가장 많이 웃은 순간은?', ARRAY['웃음','기분','일상']::text[], 'seed_61d82d35471217ab'),
  ('maid', 'icebreaker', 1, '지금 듣고 싶은 칭찬이 있다면?', ARRAY['칭찬','소통','가벼운']::text[], 'seed_a2a49efb9cacb9e2'),
  ('maid', 'icebreaker', 1, '요즘 빠져 있는 색깔이 있어?', ARRAY['색깔','취향','트렌드']::text[], 'seed_3fd7315c281aaa23'),
  ('maid', 'icebreaker', 1, '오늘 카페에서 제일 잘 나간 메뉴는?', ARRAY['메뉴','카페','메이드']::text[], 'seed_5675aec95bd8956f'),
  ('maid', 'icebreaker', 1, '마지막으로 찍은 셀카는 어떤 표정?', ARRAY['셀카','표정','재미']::text[], 'seed_06253b5272f13718'),
  ('maid', 'icebreaker', 1, '지금 이 순간 딱 하고 싶은 한마디?', ARRAY['한마디','자유','소통']::text[], 'seed_02eb07c68841c0a8'),
  ('maid', 'icebreaker', 1, '오늘 제일 먼저 눈에 띈 손님 특징은?', ARRAY['손님','관찰','메이드']::text[], 'seed_d1c6369cb611e3a6'),
  ('maid', 'icebreaker', 1, '요즘 자주 보는 SNS 앱은?', ARRAY['SNS','취향','디지털']::text[], 'seed_9a08b24790c469e9'),
  ('maid', 'icebreaker', 1, '아침형 vs 저녁형?', ARRAY['성향','선택','가벼운']::text[], 'seed_732cc1bf0d7bc125'),
  ('maid', 'icebreaker', 1, '좋아하는 계절은?', ARRAY['계절','취향','가벼운']::text[], 'seed_bad26a09e7383b48'),
  ('maid', 'icebreaker', 1, '오늘 몇 시에 일어났어?', ARRAY['기상','일상','루틴']::text[], 'seed_49d9aaee9a4b6650'),
  ('maid', 'icebreaker', 1, '카페에서 제일 좋아하는 자리는 어디?', ARRAY['카페','공간','메이드']::text[], 'seed_3274d4ca813eba35'),
  ('maid', 'icebreaker', 1, '요즘 즐겨 듣는 음악 장르는?', ARRAY['음악','장르','취향']::text[], 'seed_422da809a20836fb'),
  ('maid', 'icebreaker', 1, '오늘 컨디션을 점수로 매기면? (10점 만점)', ARRAY['컨디션','점수','가벼운']::text[], 'seed_64f2ddbbd22ebb19'),
  ('maid', 'icebreaker', 1, '지금 배고파? 배불러?', ARRAY['배고픔','상태','가벼운']::text[], 'seed_9f7913018132b09c'),
  ('maid', 'icebreaker', 1, '최근에 새로 배운 단어나 표현?', ARRAY['단어','배움','재미']::text[], 'seed_b95a43f43b822adf'),
  ('maid', 'icebreaker', 1, '좋아하는 향기가 있어?', ARRAY['향기','취향','감각']::text[], 'seed_54c17e0d4c047b7f'),
  ('maid', 'icebreaker', 1, '오늘 네일 색깔은?', ARRAY['네일','패션','디테일']::text[], 'seed_df9299c04ddf0cb8'),
  ('maid', 'icebreaker', 1, '최근 가장 많이 사용한 이모티콘은?', ARRAY['이모티콘','소통','재미']::text[], 'seed_0c7249efffddd927'),
  ('maid', 'icebreaker', 1, '오늘 점심 뭐 먹었어?', ARRAY['점심','음식','일상']::text[], 'seed_3e5b8e3be85efe83'),
  ('maid', 'icebreaker', 1, '카페 BGM으로 지금 뭐가 나오고 있어?', ARRAY['BGM','음악','카페']::text[], 'seed_b87447798c973dfc'),
  ('maid', 'icebreaker', 1, '강아지파? 고양이파?', ARRAY['동물','선택','취향']::text[], 'seed_08096c944efee3c3'),
  ('maid', 'icebreaker', 1, '지금 가장 갖고 싶은 물건 하나?', ARRAY['위시','물건','가벼운']::text[], 'seed_cdcb2dafb6372d9e'),
  ('maid', 'icebreaker', 1, '오늘 처음 만든 음료는 뭐였어?', ARRAY['음료','카페','메이드']::text[], 'seed_21a94f833cab0e14'),
  ('maid', 'icebreaker', 1, '지금 기분을 색깔로 표현하면?', ARRAY['색깔','기분','감성']::text[], 'seed_65a78ddabcb3d9af'),
  ('maid', 'icebreaker', 1, '요즘 입버릇처럼 흥얼거리는 노래?', ARRAY['노래','습관','음악']::text[], 'seed_22f564d8199c2e27'),
  ('maid', 'icebreaker', 2, '메이드 일을 시작하게 된 계기가 뭐야?', ARRAY['계기','시작','메이드','스토리']::text[], 'seed_d9d497e18e596640'),
  ('maid', 'icebreaker', 2, '손님이 기뻐할 때 가장 보람 느끼는 순간은?', ARRAY['보람','접객','감정','메이드']::text[], 'seed_a4a3c055c5ebd76e'),
  ('maid', 'icebreaker', 2, '오늘 가장 기억에 남는 주문은 뭐였어?', ARRAY['주문','에피소드','카페']::text[], 'seed_60f3fc7896fc5c08'),
  ('maid', 'icebreaker', 2, '메이드 의상 입을 때 가장 좋아하는 포인트는?', ARRAY['의상','패션','메이드','취향']::text[], 'seed_4b7bddb4b02318e2'),
  ('maid', 'icebreaker', 2, '일하면서 가장 많이 발전한 스킬이 뭐라고 생각해?', ARRAY['성장','스킬','일','자기평가']::text[], 'seed_cf8554a7c7e1344b'),
  ('maid', 'icebreaker', 2, '단골 손님이 생기면 어떤 기분이야?', ARRAY['단골','감정','접객','소통']::text[], 'seed_5ff471702913538c'),
  ('maid', 'icebreaker', 2, '쉬는 날에 주로 뭐 하면서 보내?', ARRAY['휴일','취미','일상','쉼']::text[], 'seed_b65788735c0c74ec'),
  ('maid', 'icebreaker', 2, '일하다가 실수했을 때 어떻게 수습해?', ARRAY['실수','대처','일','에피소드']::text[], 'seed_68c827d6199b4bc0'),
  ('maid', 'icebreaker', 2, '메이드로서 가장 자신 있는 메뉴 추천은?', ARRAY['메뉴','추천','자신감','카페']::text[], 'seed_ef449a01673ba463'),
  ('maid', 'icebreaker', 2, '일 끝나고 집에 가면 제일 먼저 하는 일은?', ARRAY['퇴근','루틴','일상','쉼']::text[], 'seed_e7acdced129257b0'),
  ('maid', 'icebreaker', 2, '요즘 관심 가는 취미나 배우고 싶은 것?', ARRAY['취미','관심사','배움','자기계발']::text[], 'seed_036d75ce54ce083c'),
  ('maid', 'icebreaker', 2, '손님에게 받은 칭찬 중 가장 기억에 남는 건?', ARRAY['칭찬','기억','접객','감동']::text[], 'seed_e1cbee48daa16aea'),
  ('maid', 'icebreaker', 2, '메이드 일의 의외로 힘든 부분이 있다면?', ARRAY['고충','솔직','일','현실']::text[], 'seed_7406bd3c9a977668'),
  ('maid', 'icebreaker', 2, '좋아하는 캐릭터나 마스코트가 있어?', ARRAY['캐릭터','취향','애니','서브컬처']::text[], 'seed_4e978efe7ef5b39f'),
  ('maid', 'icebreaker', 2, '손님에게 불러줄 수 있는 별명이 있다면?', ARRAY['별명','접객','소통','재미']::text[], 'seed_fbd0b0b1f804520e'),
  ('maid', 'icebreaker', 2, '카페 인테리어에서 가장 마음에 드는 부분은?', ARRAY['인테리어','카페','공간','취향']::text[], 'seed_bf763dcab49ceb0b'),
  ('maid', 'icebreaker', 2, '일할 때 긴장되는 순간이 있어?', ARRAY['긴장','일','감정','솔직']::text[], 'seed_f3b584c1c2142ae7'),
  ('maid', 'icebreaker', 2, '요즘 SNS에서 본 것 중 가장 재밌었던 건?', ARRAY['SNS','재미','트렌드','일상']::text[], 'seed_49d7801afef80ade'),
  ('maid', 'icebreaker', 2, '메이드 콘셉트 중에서 가장 해보고 싶은 테마는?', ARRAY['콘셉트','테마','메이드','상상']::text[], 'seed_a16527d815b1a2d3'),
  ('maid', 'icebreaker', 2, '이 일을 하면서 가장 놀랐던 순간은?', ARRAY['놀람','에피소드','일','발견']::text[], 'seed_53773290cbdd98bf'),
  ('maid', 'icebreaker', 2, '친구들은 메이드 일에 대해 어떻게 반응해?', ARRAY['친구','반응','일','사회']::text[], 'seed_9adf8e74ec7a62eb'),
  ('maid', 'icebreaker', 2, '일하면서 자기 자신이 변했다고 느끼는 부분?', ARRAY['변화','성장','자기성찰','일']::text[], 'seed_4b6ed6890ad14535'),
  ('maid', 'icebreaker', 2, '카페에서 특별 이벤트를 할 수 있다면 뭘 하고 싶어?', ARRAY['이벤트','아이디어','카페','상상']::text[], 'seed_303ca7b0d3a8a903'),
  ('maid', 'icebreaker', 2, '손님과 대화할 때 가장 즐거운 주제는?', ARRAY['대화','주제','접객','소통']::text[], 'seed_389fa704d5ea6731'),
  ('maid', 'icebreaker', 2, '오늘 업무 중 가장 바빴던 시간대는?', ARRAY['바쁨','업무','시간','일상']::text[], 'seed_f68cc34fd553598e'),
  ('maid', 'icebreaker', 3, '메이드라는 직업이 자기 정체성에 어떤 영향을 줬다고 생각해?', ARRAY['정체성','직업','성장','가치관']::text[], 'seed_c4ed86e48c3eb8fb'),
  ('maid', 'icebreaker', 3, '''접객''이라는 행위에서 가장 중요하다고 생각하는 건 뭐야?', ARRAY['접객','철학','가치','메이드']::text[], 'seed_b13aff1043734c7b'),
  ('maid', 'icebreaker', 3, '처음 메이드 의상을 입었을 때의 기분과 지금의 기분 차이는?', ARRAY['변화','감정','성장','메이드']::text[], 'seed_4331dad4dc481cdf'),
  ('maid', 'icebreaker', 3, '이 일을 하면서 사람에 대해 새롭게 알게 된 게 있다면?', ARRAY['인사이트','사람','배움','경험']::text[], 'seed_07042c6269ab3557'),
  ('maid', 'icebreaker', 3, '메이드 일을 다른 사람에게 추천한다면 어떤 말을 해주고 싶어?', ARRAY['조언','추천','메이드','경험담']::text[], 'seed_67a96d9aa6943cf0'),
  ('maid', 'icebreaker', 3, '손님의 미소를 보면서 어떤 감정을 느끼는지 솔직하게 말해준다면?', ARRAY['감정','손님','접객','솔직']::text[], 'seed_a5eafefeeea02c22'),
  ('maid', 'icebreaker', 3, '''좋은 메이드''란 어떤 사람이라고 생각해?', ARRAY['이상','가치관','메이드','철학']::text[], 'seed_67d0f8fe327fd267'),
  ('maid', 'icebreaker', 3, '일과 나 자신 사이에서 경계를 어떻게 유지하고 있어?', ARRAY['경계','자기관리','일','균형']::text[], 'seed_d09e01e8791adb93'),
  ('maid', 'icebreaker', 3, '5년 후에도 이 일을 하고 있을 것 같아? 아니라면 그때 뭘 하고 있을까?', ARRAY['미래','진로','상상','계획']::text[], 'seed_cf5ae1f857b07c6b'),
  ('maid', 'icebreaker', 3, '메이드 카페 문화가 더 많은 사람에게 알려진다면 어떤 점을 알려주고 싶어?', ARRAY['문화','소개','메이드','인식']::text[], 'seed_2f06f59d3db1f276'),
  ('maid', 'icebreaker', 3, '일하면서 가장 감동받았던 에피소드를 하나만 들려줄 수 있어?', ARRAY['감동','에피소드','스토리','접객']::text[], 'seed_75da3fbd476e783d'),
  ('maid', 'icebreaker', 3, '메이드로서의 나와 평소의 나, 어떤 점이 같고 어떤 점이 달라?', ARRAY['자아','비교','콘셉트','정체성']::text[], 'seed_3815ace8f5d1b72f'),
  ('maid', 'icebreaker', 3, '이 일에서 얻은 가장 큰 선물은 뭐라고 생각해?', ARRAY['선물','가치','감사','성장']::text[], 'seed_7b06ad727b702f28'),
  ('maid', 'icebreaker', 3, '손님과의 관계에서 ''거리감''은 어떻게 설정하고 있어?', ARRAY['거리감','관계','접객','경계']::text[], 'seed_14c878fea6da4f1f'),
  ('maid', 'icebreaker', 3, '지금의 나에게 처음 시작할 때의 나에게 해주고 싶은 한마디?', ARRAY['조언','과거','성장','시간']::text[], 'seed_cb877a3dc743d15f'),
  ('maid', 'daily_scene', 1, '오늘 카페 문 열기 전에 가장 먼저 한 일은?', ARRAY['오픈','준비','일상']::text[], 'seed_895cf088b5f32802'),
  ('maid', 'daily_scene', 1, '지금 카페에 손님 몇 명 정도 있어?', ARRAY['손님','현장','실시간']::text[], 'seed_142c2f40bd55178a'),
  ('maid', 'daily_scene', 1, '오늘 테이블 세팅할 때 특별히 신경 쓴 부분?', ARRAY['세팅','디테일','카페']::text[], 'seed_906f6e4d89f55b8a'),
  ('maid', 'daily_scene', 1, '지금 카페 안 온도는 어때?', ARRAY['온도','환경','현장']::text[], 'seed_ea0209d62285325f'),
  ('maid', 'daily_scene', 1, '오늘 제일 많이 주문된 메뉴는?', ARRAY['메뉴','인기','카페']::text[], 'seed_b867007caa504f07'),
  ('maid', 'daily_scene', 1, '방금 전 만든 음료는 뭐야?', ARRAY['음료','현재','카페']::text[], 'seed_0effd93d5811737a'),
  ('maid', 'daily_scene', 1, '오늘 앞치마 매듭은 어떻게 묶었어?', ARRAY['의상','디테일','메이드']::text[], 'seed_834fbacef6d2ac75'),
  ('maid', 'daily_scene', 1, '카페 창밖 풍경은 지금 어때?', ARRAY['풍경','환경','현장']::text[], 'seed_57834e03ca94ea2a'),
  ('maid', 'daily_scene', 1, '오늘 BGM 플레이리스트 테마는 뭐야?', ARRAY['BGM','음악','카페']::text[], 'seed_489385ad4b8ef9a3'),
  ('maid', 'daily_scene', 1, '지금 카운터 위에 뭐가 놓여 있어?', ARRAY['카운터','디테일','현장']::text[], 'seed_8b8cc8ecf5cef54b'),
  ('maid', 'daily_scene', 1, '오늘 사용한 시럽 중 가장 좋아하는 맛은?', ARRAY['시럽','맛','카페']::text[], 'seed_ba8ca360863dd2c4'),
  ('maid', 'daily_scene', 1, '지금 손에 들고 있는 건 뭐야?', ARRAY['현재','디테일','실시간']::text[], 'seed_de9f82cd81b41685'),
  ('maid', 'daily_scene', 1, '오늘 청소할 때 가장 공들인 곳은?', ARRAY['청소','준비','일상']::text[], 'seed_ace8369aa6e7a59c'),
  ('maid', 'daily_scene', 1, '카페에서 가장 아끼는 소품이 있어?', ARRAY['소품','카페','애착']::text[], 'seed_699b99d0cf74c5e6'),
  ('maid', 'daily_scene', 1, '오늘 웃긴 일이 하나라도 있었어?', ARRAY['웃김','에피소드','일상']::text[], 'seed_5fe0b1754e8a0273'),
  ('maid', 'daily_scene', 1, '지금 신고 있는 실내화는 어떤 거야?', ARRAY['신발','의상','디테일']::text[], 'seed_643678d9ec010a00'),
  ('maid', 'daily_scene', 1, '오늘 카페에 새로 들어온 재료가 있어?', ARRAY['재료','신메뉴','카페']::text[], 'seed_32ed03ec291e2723'),
  ('maid', 'daily_scene', 1, '지금 가장 깨끗한 테이블 번호는?', ARRAY['테이블','청결','현장']::text[], 'seed_fca43f403e681d30'),
  ('maid', 'daily_scene', 1, '오늘 제일 예쁘게 나온 라떼아트는?', ARRAY['라떼아트','스킬','카페']::text[], 'seed_a1234731f4129b32'),
  ('maid', 'daily_scene', 1, '카페 냉장고 안에 지금 뭐가 있어?', ARRAY['냉장고','재료','현장']::text[], 'seed_afa87fc357c16571'),
  ('maid', 'daily_scene', 1, '오늘 손님이 가장 많았던 시간은?', ARRAY['피크','시간','업무']::text[], 'seed_edb1fc5df9109503'),
  ('maid', 'daily_scene', 1, '지금 카페에 떠도는 향기는?', ARRAY['향기','환경','감각']::text[], 'seed_a6a50db06c24b581'),
  ('maid', 'daily_scene', 1, '오늘 접시 깨진 거 없지?', ARRAY['접시','해프닝','일상']::text[], 'seed_fcae2f72095b45a2'),
  ('maid', 'daily_scene', 1, '카페 앞 간판 오늘 뭐라고 적혀 있어?', ARRAY['간판','카페','디테일']::text[], 'seed_7fab42637551c805'),
  ('maid', 'daily_scene', 1, '오늘 가장 복잡했던 주문은?', ARRAY['주문','에피소드','업무']::text[], 'seed_fd848ef0238e1775'),
  ('maid', 'daily_scene', 1, '지금 에어컨(히터) 온도 몇 도로 맞춰놨어?', ARRAY['온도','환경','디테일']::text[], 'seed_28bb234340ed3854'),
  ('maid', 'daily_scene', 1, '오늘 카페 오픈 시간은 몇 시였어?', ARRAY['오픈','시간','일상']::text[], 'seed_4b800c2ae4ed4fb3'),
  ('maid', 'daily_scene', 1, '테이블 위 꽃이나 장식 오늘 바꿨어?', ARRAY['장식','디테일','카페']::text[], 'seed_e5d59f9cb8409624'),
  ('maid', 'daily_scene', 1, '오늘 제일 먼저 온 손님은 몇 시에 왔어?', ARRAY['첫손님','시간','일상']::text[], 'seed_f0aeb3af215c7ddf'),
  ('maid', 'daily_scene', 1, '지금 카페 조명은 어떤 분위기야?', ARRAY['조명','분위기','환경']::text[], 'seed_b0bec7d024ce49e6'),
  ('maid', 'daily_scene', 1, '오늘 설거지 몇 번 했어?', ARRAY['설거지','업무','일상']::text[], 'seed_75399adb2f1eaa02'),
  ('maid', 'daily_scene', 1, '카페에 반려식물이 있어?', ARRAY['식물','카페','디테일']::text[], 'seed_2222b1654cd47d65'),
  ('maid', 'daily_scene', 1, '오늘 가장 이쁘게 플레이팅한 디저트는?', ARRAY['디저트','플레이팅','카페']::text[], 'seed_53cc12405176eb8e'),
  ('maid', 'daily_scene', 1, '지금 카페 밖 날씨는 어때?', ARRAY['날씨','환경','현장']::text[], 'seed_ec6c27489d3396aa'),
  ('maid', 'daily_scene', 1, '오늘 컵 세척 몇 개쯤 했어?', ARRAY['세척','업무','숫자']::text[], 'seed_802b2b99481cb301'),
  ('maid', 'daily_scene', 1, '카페 메뉴판에서 제일 마음에 드는 글씨체는?', ARRAY['메뉴판','디자인','카페']::text[], 'seed_eb47e6a869fc1b17'),
  ('maid', 'daily_scene', 1, '오늘 택배나 배송 온 거 있어?', ARRAY['택배','일상','카페']::text[], 'seed_9ee3ace9e76449e1'),
  ('maid', 'daily_scene', 1, '지금 스피커에서 나오는 노래 제목 알아?', ARRAY['노래','BGM','현장']::text[], 'seed_e914a6d105c9a635'),
  ('maid', 'daily_scene', 1, '오늘 티 타임에 가장 인기 있는 차 종류는?', ARRAY['차','인기','카페']::text[], 'seed_4c4bf67dfe02584f'),
  ('maid', 'daily_scene', 1, '카페 화장실에 오늘 비치한 향기는?', ARRAY['향기','디테일','카페']::text[], 'seed_b88cb8a18b2aa218'),
  ('maid', 'daily_scene', 2, '오늘 하루의 업무 흐름을 간단히 타임라인으로 설명해줄 수 있어?', ARRAY['타임라인','업무','일상','구조']::text[], 'seed_cbb818acdf1a685a'),
  ('maid', 'daily_scene', 2, '카페 오픈 준비 과정에서 가장 중요하게 생각하는 단계는?', ARRAY['오픈','준비','프로세스','가치']::text[], 'seed_3666c8ca8f6408f0'),
  ('maid', 'daily_scene', 2, '오늘 손님과 나눈 대화 중 인상 깊었던 건?', ARRAY['대화','손님','에피소드','소통']::text[], 'seed_f2a49a6146789be2'),
  ('maid', 'daily_scene', 2, '메뉴 신작을 개발한다면 어떤 걸 만들고 싶어?', ARRAY['신메뉴','아이디어','카페','창의']::text[], 'seed_e848acc30d2cc8e8'),
  ('maid', 'daily_scene', 2, '바쁜 시간대와 한가한 시간대, 각각 어떤 기분이야?', ARRAY['시간대','감정','업무','비교']::text[], 'seed_1bddceb83a4d08cf'),
  ('maid', 'daily_scene', 2, '카페 인테리어를 하나 바꿀 수 있다면 뭘 바꾸고 싶어?', ARRAY['인테리어','아이디어','카페','변화']::text[], 'seed_50c569fd9073d9e2'),
  ('maid', 'daily_scene', 2, '손님이 떠난 후 테이블 정리하면서 어떤 생각을 해?', ARRAY['정리','생각','일상','감정']::text[], 'seed_51b7e68cea944e28'),
  ('maid', 'daily_scene', 2, '카페에서 가장 좋아하는 시간대와 그 이유는?', ARRAY['시간대','취향','카페','이유']::text[], 'seed_736948ce3ecd0ebb'),
  ('maid', 'daily_scene', 2, '음료 만들 때 자기만의 비법이나 습관이 있어?', ARRAY['비법','음료','스킬','카페']::text[], 'seed_b3a5c133f2858433'),
  ('maid', 'daily_scene', 2, '오늘 일하면서 가장 뿌듯했던 순간은?', ARRAY['뿌듯','성취','일상','감정']::text[], 'seed_970f703e56e82e63'),
  ('maid', 'daily_scene', 2, '카페 동료와 오늘 나눈 재밌는 대화가 있어?', ARRAY['동료','대화','재미','일상']::text[], 'seed_0bbad8a79def6e3b'),
  ('maid', 'daily_scene', 2, '새로운 손님이 왔을 때 첫인상은 어떻게 파악하는 편이야?', ARRAY['첫인상','관찰','접객','스킬']::text[], 'seed_6f497b74eca9c72f'),
  ('maid', 'daily_scene', 2, '메이드 카페만의 특별한 서비스 중 가장 자신 있는 건?', ARRAY['서비스','자신감','메이드','스킬']::text[], 'seed_40a2da6926ea8acf'),
  ('maid', 'daily_scene', 2, '퇴근 후 카페에서의 하루를 되돌아볼 때 어떤 기분이야?', ARRAY['퇴근','회고','감정','일상']::text[], 'seed_840911c07eade767'),
  ('maid', 'daily_scene', 2, '카페에서 쓰는 도구(머신/도구) 중 가장 애착 가는 건?', ARRAY['도구','애착','카페','직업']::text[], 'seed_b5b987eea7a4376a'),
  ('maid', 'daily_scene', 2, '혼자 오는 손님과 단체 손님, 접객 방식이 달라?', ARRAY['접객','방식','비교','스킬']::text[], 'seed_87b288d83611b368'),
  ('maid', 'daily_scene', 2, '오늘 카페 매출이 평소보다 좋았어? 분위기로 느낄 수 있어?', ARRAY['매출','분위기','감각','업무']::text[], 'seed_12b9dc0fa8099333'),
  ('maid', 'daily_scene', 2, '카페에서 가장 조용한 코너는 어디야? 그곳의 매력은?', ARRAY['공간','코너','카페','매력']::text[], 'seed_0622e6b3dc469e26'),
  ('maid', 'daily_scene', 2, '오늘 실수하거나 당황한 순간이 있었어?', ARRAY['실수','당황','에피소드','솔직']::text[], 'seed_9b1dc258cacf744e'),
  ('maid', 'daily_scene', 2, '메뉴 사진 찍을 때 자기만의 앵글이나 팁이 있어?', ARRAY['사진','팁','메뉴','SNS']::text[], 'seed_684e10eb78b2630b'),
  ('maid', 'daily_scene', 2, '카페에서 꼭 유지하고 싶은 분위기나 룰이 있다면?', ARRAY['분위기','룰','가치','카페']::text[], 'seed_efa8f751a93b7430'),
  ('maid', 'daily_scene', 2, '오늘 디저트 플레이팅하면서 어떤 생각을 했어?', ARRAY['디저트','플레이팅','생각','일상']::text[], 'seed_15a325bbd5f806a7'),
  ('maid', 'daily_scene', 2, '계절이 바뀔 때 카페에서 가장 먼저 변하는 건 뭐야?', ARRAY['계절','변화','카페','관찰']::text[], 'seed_c6289867f7b9a30f'),
  ('maid', 'daily_scene', 2, '단골 손님과 처음 온 손님, 대하는 방식에 차이가 있어?', ARRAY['단골','신규','접객','비교']::text[], 'seed_d75f6e94adc2bbe3'),
  ('maid', 'daily_scene', 2, '오늘 카페에서 찍은 사진 중 가장 마음에 드는 건?', ARRAY['사진','오늘','카페','기록']::text[], 'seed_088c43c0f033ff31'),
  ('maid', 'daily_scene', 3, '하루 동안 카페에서 느끼는 감정의 변화를 솔직하게 이야기해줄 수 있어?', ARRAY['감정','변화','솔직','일상']::text[], 'seed_51074f12d5fde701'),
  ('maid', 'daily_scene', 3, '카페라는 공간이 자기에게 어떤 의미가 있는지 이야기해준다면?', ARRAY['공간','의미','가치','카페']::text[], 'seed_daeb22042cb8ca6a'),
  ('maid', 'daily_scene', 3, '손님이 떠난 후 빈 카페에 혼자 있을 때의 기분은 어때?', ARRAY['혼자','공간','감정','마감']::text[], 'seed_f6881c9134040cbe'),
  ('maid', 'daily_scene', 3, '카페에서의 하루가 자기 삶의 리듬에 어떤 영향을 주고 있어?', ARRAY['리듬','삶','영향','일상']::text[], 'seed_94966176aad543f6'),
  ('maid', 'daily_scene', 3, '완벽한 하루의 카페 영업은 어떤 모습일까?', ARRAY['이상','완벽','카페','상상']::text[], 'seed_24dde8b4dfdf7e81'),
  ('maid', 'daily_scene', 3, '카페에서 만난 사람들이 자기 세계관에 어떤 영향을 줬어?', ARRAY['사람','영향','세계관','성장']::text[], 'seed_e0cf0b56596e4109'),
  ('maid', 'daily_scene', 3, '일상적인 업무(세척, 정리 등)를 하면서 명상 같은 기분이 드는 순간이 있어?', ARRAY['명상','업무','감각','일상']::text[], 'seed_a736945108abda64'),
  ('maid', 'daily_scene', 3, '카페의 사계절 중 가장 좋아하는 시기와 그때의 풍경을 묘사해준다면?', ARRAY['계절','풍경','카페','묘사']::text[], 'seed_b36782b48c7a2229'),
  ('maid', 'daily_scene', 3, '오늘 하루를 한 편의 짧은 이야기로 만든다면 제목은 뭐가 될까?', ARRAY['제목','스토리','창의','회고']::text[], 'seed_b426accf03e8f917'),
  ('maid', 'daily_scene', 3, '카페에서 일하면서 ''시간''에 대한 감각이 변한 부분이 있어?', ARRAY['시간','감각','변화','철학']::text[], 'seed_dba4e30da9fbdc17'),
  ('maid', 'daily_scene', 3, '가장 기억에 남는 ''카페의 하루''를 처음부터 끝까지 이야기해줄 수 있어?', ARRAY['에피소드','기억','스토리','카페']::text[], 'seed_ec0d4e090742dbc5'),
  ('maid', 'daily_scene', 3, '카페 마감 후 불을 끌 때의 기분을 자세히 말해준다면?', ARRAY['마감','감정','순간','카페']::text[], 'seed_aa0fd63e262dc6e6'),
  ('maid', 'daily_scene', 3, '매일 반복되는 업무에서 매일 다르게 느껴지는 건 뭐야?', ARRAY['반복','차이','관찰','일상']::text[], 'seed_ae46cf97fb1888be'),
  ('maid', 'daily_scene', 3, '카페라는 공간을 떠나게 된다면 가장 그리울 것 같은 순간은?', ARRAY['그리움','이별','카페','감정']::text[], 'seed_fb3834b1ca2ac21b'),
  ('maid', 'daily_scene', 3, '오늘 하루를 색깔과 향기로 표현한다면 어떤 조합이야?', ARRAY['색깔','향기','감각','표현']::text[], 'seed_8cf184fb375732dc'),
  ('maid', 'behind_story', 1, '메이드 카페를 처음 알게 된 건 언제야?', ARRAY['처음','발견','계기']::text[], 'seed_a87a6c33950ece11'),
  ('maid', 'behind_story', 1, '첫 출근 날 가장 기억나는 건?', ARRAY['첫출근','기억','에피소드']::text[], 'seed_579afa66e0ad33b7'),
  ('maid', 'behind_story', 1, '처음 만든 음료는 뭐였어?', ARRAY['첫음료','시작','카페']::text[], 'seed_56d66aeecd532b1d'),
  ('maid', 'behind_story', 1, '메이드 의상 처음 입어본 날 누구한테 먼저 보여줬어?', ARRAY['의상','처음','반응']::text[], 'seed_e5eefe46626c8217'),
  ('maid', 'behind_story', 1, '이 일 전에 해본 아르바이트가 있어?', ARRAY['이전','아르바이트','경험']::text[], 'seed_0be7212b05b902ee'),
  ('maid', 'behind_story', 1, '면접 때 가장 긴장됐던 질문은?', ARRAY['면접','긴장','에피소드']::text[], 'seed_e30ced77e702a3e4'),
  ('maid', 'behind_story', 1, '처음 손님에게 인사했을 때 떨렸어?', ARRAY['첫인사','긴장','시작']::text[], 'seed_6bb4d62396974021'),
  ('maid', 'behind_story', 1, '메이드 이름(닉네임)은 어떻게 정했어?', ARRAY['닉네임','유래','메이드']::text[], 'seed_f35083f3d488aa83'),
  ('maid', 'behind_story', 1, '연습할 때 가장 어려웠던 서비스 스킬은?', ARRAY['연습','스킬','어려움']::text[], 'seed_99fd99fbd9c508fe'),
  ('maid', 'behind_story', 1, '처음 팁(칭찬)을 받았을 때 기분은?', ARRAY['칭찬','처음','감정']::text[], 'seed_a9b42dc0e02d1553'),
  ('maid', 'behind_story', 1, '어린 시절 꿈은 뭐였어?', ARRAY['꿈','어린시절','배경']::text[], 'seed_794dfc07d335b27b'),
  ('maid', 'behind_story', 1, '메이드 카페에 관심 갖게 된 이유가 서브컬처 때문이야?', ARRAY['서브컬처','관심','계기']::text[], 'seed_5f4866b4e9183c96'),
  ('maid', 'behind_story', 1, '학생 때 좋아했던 과목은?', ARRAY['학생','과목','과거']::text[], 'seed_21bdb364a2732b6d'),
  ('maid', 'behind_story', 1, '메이드 일 하기 전 자기 성격을 한마디로?', ARRAY['성격','과거','자기소개']::text[], 'seed_f2a73ed9e1a48a38'),
  ('maid', 'behind_story', 1, '가족은 이 일에 대해 알고 있어?', ARRAY['가족','반응','일']::text[], 'seed_a30858f9d767343a'),
  ('maid', 'behind_story', 1, '처음 라떼아트 성공했을 때 모양은?', ARRAY['라떼아트','성공','처음']::text[], 'seed_708161c9e9113dd9'),
  ('maid', 'behind_story', 1, '메이드 카페를 처음 방문한 건 손님으로서? 아니면 바로 일을 시작?', ARRAY['처음방문','계기','순서']::text[], 'seed_4ab336ed0c628502'),
  ('maid', 'behind_story', 1, '트레이닝 기간은 얼마나 됐어?', ARRAY['트레이닝','기간','시작']::text[], 'seed_c3ffd1d483269ef0'),
  ('maid', 'behind_story', 1, '처음 일하면서 가장 당황했던 상황은?', ARRAY['당황','처음','에피소드']::text[], 'seed_a077c9e06aaf7b99'),
  ('maid', 'behind_story', 1, '이 일을 시작할 때 주변 반응은 어땠어?', ARRAY['주변','반응','시작']::text[], 'seed_ecb9b3c83e4e04b8'),
  ('maid', 'behind_story', 1, '메이드 문화를 알게 된 매체는? (애니/만화/SNS 등)', ARRAY['매체','발견','서브컬처']::text[], 'seed_3a0a78a63ca7daf6'),
  ('maid', 'behind_story', 1, '첫 월급으로 뭐 했어?', ARRAY['첫월급','기억','소비']::text[], 'seed_7c732044e52e43e8'),
  ('maid', 'behind_story', 1, '일 시작하고 가장 먼저 친해진 동료는 어떤 사람이었어?', ARRAY['동료','친분','시작']::text[], 'seed_ff1b8b20e7a7ad7c'),
  ('maid', 'behind_story', 1, '처음 단골이 생겼을 때 어떤 기분이었어?', ARRAY['단골','처음','감정']::text[], 'seed_efb543dd87a6d87e'),
  ('maid', 'behind_story', 1, '메이드 활동명 외에 후보였던 이름이 있어?', ARRAY['활동명','후보','재미']::text[], 'seed_fcd86adab00678c2'),
  ('maid', 'behind_story', 1, '일 시작 전에 메이드 카페에 대한 이미지는 어땠어?', ARRAY['이미지','선입견','변화']::text[], 'seed_cfaffae7b3606151'),
  ('maid', 'behind_story', 1, '처음 메이크업 연습할 때 어땠어?', ARRAY['메이크업','연습','시작']::text[], 'seed_08a73b8cb4041986'),
  ('maid', 'behind_story', 1, '이 일의 매력을 처음 느낀 구체적 순간은?', ARRAY['매력','발견','순간']::text[], 'seed_4cee8d7a672366fc'),
  ('maid', 'behind_story', 1, '첫 이벤트(생일/기념일 등)에 참여했을 때 느낌은?', ARRAY['이벤트','처음','감정']::text[], 'seed_52899f42392b23c7'),
  ('maid', 'behind_story', 1, '메이드 일 시작하고 가장 먼저 변한 습관은?', ARRAY['습관','변화','시작']::text[], 'seed_d3edf2fd7af61ddc'),
  ('maid', 'behind_story', 1, '채용 공고를 보고 지원한 거야, 아니면 추천?', ARRAY['지원','계기','시작']::text[], 'seed_e9bc98f4727786d4'),
  ('maid', 'behind_story', 1, '첫 날 실수한 에피소드가 있어?', ARRAY['첫날','실수','에피소드']::text[], 'seed_3d783f34795aea74'),
  ('maid', 'behind_story', 1, '메이드 일 하기 전 커피에 관심 있었어?', ARRAY['커피','관심','이전']::text[], 'seed_de1a96806aae3927'),
  ('maid', 'behind_story', 1, '처음 혼자 오픈(마감) 맡았을 때 기분은?', ARRAY['혼자','책임','처음']::text[], 'seed_3a87da2e7ebaab08'),
  ('maid', 'behind_story', 1, '첫 번째 ''단골''이 된 메뉴가 있어? (자기가 자주 만드는)', ARRAY['메뉴','자주','카페']::text[], 'seed_9324b5b4a1fed405'),
  ('maid', 'behind_story', 1, '메이드 카페 면접에서 자기 PR은 뭐라고 했어?', ARRAY['면접','PR','자기소개']::text[], 'seed_0d7285afd67e4bb7'),
  ('maid', 'behind_story', 1, '이 일을 시작한 나이는?', ARRAY['나이','시작','시기']::text[], 'seed_ffa5046c8a345972'),
  ('maid', 'behind_story', 1, '처음 손님에게 ''감사합니다'' 말할 때 어색했어?', ARRAY['인사','어색함','시작']::text[], 'seed_be0501a365deb7da'),
  ('maid', 'behind_story', 1, '메이드 일 시작 전 좋아했던 애니나 만화는?', ARRAY['애니','만화','취향']::text[], 'seed_c8914784bbc2961f'),
  ('maid', 'behind_story', 1, '이 일을 시작하겠다고 결심한 결정적 한마디(또는 계기)는?', ARRAY['결심','계기','시작']::text[], 'seed_e75cab63d74d3af7'),
  ('maid', 'behind_story', 2, '메이드 일을 시작하기 전과 후, 자기 자신에 대한 인식이 어떻게 변했어?', ARRAY['변화','자기인식','성장','비교']::text[], 'seed_f4b61a5440daf48c'),
  ('maid', 'behind_story', 2, '트레이닝 기간 중 가장 기억에 남는 에피소드는?', ARRAY['트레이닝','에피소드','성장','기억']::text[], 'seed_279ae8906a6709f6'),
  ('maid', 'behind_story', 2, '이 일을 시작하면서 잃은 것과 얻은 것이 있다면?', ARRAY['득실','변화','솔직','성장']::text[], 'seed_e8d98e3050b24399'),
  ('maid', 'behind_story', 2, '선배 메이드에게서 배운 가장 인상적인 조언은?', ARRAY['선배','조언','배움','메이드']::text[], 'seed_94141641e2fc684c'),
  ('maid', 'behind_story', 2, '첫 이벤트를 기획해봤을 때의 과정과 결과는?', ARRAY['이벤트','기획','경험','성장']::text[], 'seed_8b7cc18837608d75'),
  ('maid', 'behind_story', 2, '메이드 카페 업계에 대한 오해 중 바로잡고 싶은 게 있다면?', ARRAY['오해','인식','메이드','사회']::text[], 'seed_dbf1e3cdd1ed5877'),
  ('maid', 'behind_story', 2, '가장 힘들었던 시기는 언제였고, 어떻게 넘겼어?', ARRAY['힘듦','극복','시기','성장']::text[], 'seed_6336ea28330d584a'),
  ('maid', 'behind_story', 2, '메이드 활동을 하면서 새로 생긴 꿈이나 목표가 있어?', ARRAY['꿈','목표','미래','변화']::text[], 'seed_78d91b4940b17130'),
  ('maid', 'behind_story', 2, '다른 메이드들과 비교했을 때 자기만의 강점이라고 생각하는 건?', ARRAY['강점','차별점','자기평가','메이드']::text[], 'seed_46ecf40ed8507427'),
  ('maid', 'behind_story', 2, '카페에서 있었던 가장 감동적인 에피소드는?', ARRAY['감동','에피소드','스토리','접객']::text[], 'seed_583b77674ddd508a'),
  ('maid', 'behind_story', 2, '이 일을 하면서 대인관계 스킬이 어떻게 변했어?', ARRAY['대인관계','스킬','변화','성장']::text[], 'seed_8c1385a2ddb04ba5'),
  ('maid', 'behind_story', 2, '메이드 콘셉트를 잡을 때 참고한 캐릭터나 영감이 있어?', ARRAY['콘셉트','영감','캐릭터','창작']::text[], 'seed_7181edbbab0af4f2'),
  ('maid', 'behind_story', 2, '이 업계에서 일하면서 가장 성장했다고 느끼는 스킬은?', ARRAY['성장','스킬','경험','자기평가']::text[], 'seed_d3b291e61b1dfbc7'),
  ('maid', 'behind_story', 2, '메이드 일을 그만두고 싶었던 순간이 있었다면?', ARRAY['그만두고싶음','솔직','고민','극복']::text[], 'seed_f5e66b81e24b91bb'),
  ('maid', 'behind_story', 2, '가장 재미있었던 카페 이벤트의 뒷이야기를 들려줘!', ARRAY['이벤트','비하인드','재미','에피소드']::text[], 'seed_0f695ee625861842'),
  ('maid', 'behind_story', 2, '처음 팬(단골)이 생겼을 때 기분과 책임감에 대해 이야기해줄래?', ARRAY['팬','단골','감정','책임감']::text[], 'seed_bc1b25506f2427d1'),
  ('maid', 'behind_story', 2, '메이드 의상 이외에 해보고 싶은 콘셉트 의상이 있어?', ARRAY['의상','콘셉트','상상','패션']::text[], 'seed_8a4fa8339afd0701'),
  ('maid', 'behind_story', 2, '이 일을 하면서 가장 크게 성장한 시점은 언제라고 생각해?', ARRAY['성장','시점','자기성찰','변화']::text[], 'seed_32798ed2f977c0bf'),
  ('maid', 'behind_story', 2, '카페 밖에서 메이드 일 경험이 도움이 된 적 있어?', ARRAY['경험','활용','일상','스킬']::text[], 'seed_856a058a2c5e3727'),
  ('maid', 'behind_story', 2, '후배가 들어왔을 때 가장 먼저 가르쳐주는 건 뭐야?', ARRAY['후배','가르침','노하우','메이드']::text[], 'seed_6e2ddd0d81c1b857'),
  ('maid', 'behind_story', 2, '메이드 업계에서만 쓰는 독특한 용어나 은어가 있어?', ARRAY['용어','은어','업계','재미']::text[], 'seed_6dce4952e3305408'),
  ('maid', 'behind_story', 2, '자기만의 ''시그니처 서비스''가 있다면 뭐야?', ARRAY['시그니처','서비스','차별화','메이드']::text[], 'seed_51aa2f39e58c2787'),
  ('maid', 'behind_story', 2, '메이드 활동 중 SNS에서 가장 반응이 좋았던 게시물은?', ARRAY['SNS','반응','기록','활동']::text[], 'seed_46e9e3d132dd1521'),
  ('maid', 'behind_story', 2, '이 일에서 가장 예상 못 했던 즐거움은?', ARRAY['예상밖','즐거움','발견','일']::text[], 'seed_fe764481c529c7e8'),
  ('maid', 'behind_story', 2, '처음 ''진짜 메이드가 됐다''고 느낀 순간은?', ARRAY['자격','순간','성장','정체성']::text[], 'seed_76b39c422d5efba0'),
  ('maid', 'behind_story', 3, '메이드 카페 문화가 자기 인생에서 어떤 챕터에 해당한다고 생각해?', ARRAY['인생','챕터','의미','철학']::text[], 'seed_4cae591cc14f5e42'),
  ('maid', 'behind_story', 3, '이 일을 통해 ''사람''에 대해 가장 깊이 배운 것은?', ARRAY['사람','배움','인사이트','성장']::text[], 'seed_22e45d7f1e0af499'),
  ('maid', 'behind_story', 3, '메이드로서의 커리어를 한 편의 성장 스토리로 요약한다면?', ARRAY['커리어','성장','스토리','요약']::text[], 'seed_de809cadab503caf'),
  ('maid', 'behind_story', 3, '이 일을 하면서 자기가 가장 변화한 ''가치관''은 뭐야?', ARRAY['가치관','변화','성장','철학']::text[], 'seed_706593a86cb3b310'),
  ('maid', 'behind_story', 3, '메이드 문화가 사회에 기여하는 점이 있다고 생각해?', ARRAY['사회','기여','메이드','가치']::text[], 'seed_88aaeb758a6654e5'),
  ('maid', 'behind_story', 3, '이 업계에서의 경험이 자기 다음 챕터에 어떤 도움이 될 거라 생각해?', ARRAY['미래','도움','경험','연결']::text[], 'seed_9c5d9451262af96f'),
  ('maid', 'behind_story', 3, '가장 힘들었던 시기의 자기에게 편지를 쓴다면 뭐라고 할래?', ARRAY['편지','과거','위로','성장']::text[], 'seed_e1cf0d36a86be969'),
  ('maid', 'behind_story', 3, '메이드 카페를 운영하는 사람이 된다면 어떤 카페를 만들고 싶어?', ARRAY['운영','이상','카페','비전']::text[], 'seed_cc3292b2c5b89307'),
  ('maid', 'behind_story', 3, '이 일에서 얻은 경험 중 평생 간직하고 싶은 건?', ARRAY['경험','간직','가치','소중']::text[], 'seed_a447bc93e54abafc'),
  ('maid', 'behind_story', 3, '메이드 카페 문화를 모르는 사람에게 이 세계를 설명한다면?', ARRAY['설명','문화','소개','외부']::text[], 'seed_0c84a9ead181be5e'),
  ('maid', 'behind_story', 3, '이 일을 하면서 ''내가 생각하는 프로페셔널리즘''이 변했어?', ARRAY['프로','직업관','변화','성장']::text[], 'seed_c35115a4c32f85ab'),
  ('maid', 'behind_story', 3, '10년 후, 이 시절을 돌아본다면 어떤 기억이 가장 먼저 떠오를 것 같아?', ARRAY['10년후','기억','미래','회고']::text[], 'seed_ccefe2b6d5a077ff'),
  ('maid', 'behind_story', 3, '메이드 카페 문화의 미래는 어떻게 될 거라 생각해?', ARRAY['미래','문화','전망','메이드']::text[], 'seed_0708adcf26ea4717'),
  ('maid', 'behind_story', 3, '이 일에서의 경험을 책으로 쓴다면 제목은 뭐가 될까?', ARRAY['책','제목','스토리','창의']::text[], 'seed_e25f4cc524efeeff'),
  ('maid', 'behind_story', 3, '메이드 일을 하면서 발견한 ''자기 자신의 의외의 면''은?', ARRAY['자기발견','의외','성장','정체성']::text[], 'seed_39264127029dd807'),
  ('maid', 'roleplay_flavor', 1, '지금 마법으로 하나만 소환할 수 있다면 뭘 부를 거야?', ARRAY['마법','소환','상상','재미']::text[], 'seed_365a1f4acdd99639'),
  ('maid', 'roleplay_flavor', 1, '''오늘의 특별 주문''을 콘셉트로 만든다면 이름은?', ARRAY['메뉴','콘셉트','창의','카페']::text[], 'seed_eac97de35a72b3e7'),
  ('maid', 'roleplay_flavor', 1, '카페에 요정이 살고 있다면 어디에 숨어 있을까?', ARRAY['요정','상상','카페','귀여움']::text[], 'seed_02bc1be5e2752d30'),
  ('maid', 'roleplay_flavor', 1, '손님에게 마법의 인사를 건넨다면 뭐라고 할까?', ARRAY['인사','마법','콘셉트','접객']::text[], 'seed_c8169e1821b7d2e4'),
  ('maid', 'roleplay_flavor', 1, '오늘의 메이드 칭호를 하나 만든다면?', ARRAY['칭호','콘셉트','재미','메이드']::text[], 'seed_fe57cc937f7edafe'),
  ('maid', 'roleplay_flavor', 1, '카페 마스코트를 만든다면 어떤 동물이야?', ARRAY['마스코트','동물','상상','카페']::text[], 'seed_6c33eb6175d640b7'),
  ('maid', 'roleplay_flavor', 1, '오늘 사용할 마법 주문 한마디를 만들어줘!', ARRAY['주문','마법','창의','재미']::text[], 'seed_700146584575e937'),
  ('maid', 'roleplay_flavor', 1, '비밀 메뉴가 있다면 이름과 재료는?', ARRAY['비밀메뉴','상상','카페','창의']::text[], 'seed_87b5e85c4111104c'),
  ('maid', 'roleplay_flavor', 1, '오늘의 럭키 아이템을 하나 정해준다면?', ARRAY['럭키','아이템','운세','재미']::text[], 'seed_5a7367096bbb1f12'),
  ('maid', 'roleplay_flavor', 1, '카페에 비밀 통로가 있다면 어디로 이어질까?', ARRAY['비밀통로','상상','판타지','카페']::text[], 'seed_55d41d62a6cc870c'),
  ('maid', 'roleplay_flavor', 1, '요일마다 다른 콘셉트라면 오늘은 무슨 요일 콘셉트?', ARRAY['요일','콘셉트','상상','메이드']::text[], 'seed_e8a810a615dd2f45'),
  ('maid', 'roleplay_flavor', 1, '손님에게 줄 수 있는 ''버프'' 한 가지는?', ARRAY['버프','게임','상상','재미']::text[], 'seed_7b211f449e4d4725'),
  ('maid', 'roleplay_flavor', 1, '카페 BGM을 마법으로 바꿀 수 있다면 어떤 장르로?', ARRAY['BGM','마법','음악','상상']::text[], 'seed_f191a946b3a29a53'),
  ('maid', 'roleplay_flavor', 1, '자기만의 변신 포즈를 하나 만든다면?', ARRAY['변신','포즈','콘셉트','재미']::text[], 'seed_eea77881c2fb9be8'),
  ('maid', 'roleplay_flavor', 1, '오늘의 행운 컬러를 하나 지정해준다면?', ARRAY['행운','컬러','운세','재미']::text[], 'seed_20eb94bc929e91d4'),
  ('maid', 'roleplay_flavor', 1, '카페 메뉴에 마법 효과가 있다면 어떤 효과?', ARRAY['마법','메뉴','효과','상상']::text[], 'seed_79d0b5b558f08d60'),
  ('maid', 'roleplay_flavor', 1, '메이드 모드 ON! 지금 전투력은 몇 퍼센트?', ARRAY['전투력','게임','상태','재미']::text[], 'seed_61af1d50db9e3aed'),
  ('maid', 'roleplay_flavor', 1, '오늘의 메이드 테마곡을 하나 정한다면?', ARRAY['테마곡','음악','콘셉트','선택']::text[], 'seed_bb1fe4853dbf8f8d'),
  ('maid', 'roleplay_flavor', 1, '마법의 앞치마에 숨겨진 능력이 있다면?', ARRAY['앞치마','마법','능력','상상']::text[], 'seed_232dc650ad3b99f6'),
  ('maid', 'roleplay_flavor', 1, '손님을 맞이하는 나만의 시그니처 제스처는?', ARRAY['제스처','시그니처','접객','콘셉트']::text[], 'seed_ee7ef687550bbd3b'),
  ('maid', 'roleplay_flavor', 1, 'RPG에서 메이드 클래스의 특수 스킬명은?', ARRAY['RPG','스킬','게임','상상']::text[], 'seed_08f8028f6758c432'),
  ('maid', 'roleplay_flavor', 1, '카페가 우주선이라면 자기 역할은?', ARRAY['우주','역할','상상','SF']::text[], 'seed_18528098be5a4ad2'),
  ('maid', 'roleplay_flavor', 1, '메이드 카페 공식 응원구호를 만든다면?', ARRAY['응원','구호','콘셉트','팀']::text[], 'seed_5215aa2db2dd2899'),
  ('maid', 'roleplay_flavor', 1, '오늘 손님에게 줄 ''작은 행복 쿠폰'' 내용은?', ARRAY['쿠폰','행복','선물','상상']::text[], 'seed_3872ed0e6306ef54'),
  ('maid', 'roleplay_flavor', 1, '마법소녀로 변신한다면 무기는 뭐야?', ARRAY['마법소녀','무기','변신','상상']::text[], 'seed_42da79b325e7be06'),
  ('maid', 'roleplay_flavor', 1, '오늘의 메이드 운세를 한마디로?', ARRAY['운세','한마디','재미','콘셉트']::text[], 'seed_2fb580dc0988272c'),
  ('maid', 'roleplay_flavor', 1, '카페 안에 숨겨진 보물이 있다면 어디에?', ARRAY['보물','숨김','상상','카페']::text[], 'seed_a7c6234f4f51500e'),
  ('maid', 'roleplay_flavor', 1, '자기를 동물로 표현하면 뭐야?', ARRAY['동물','자기표현','상상','성격']::text[], 'seed_810b9afb7a357449'),
  ('maid', 'roleplay_flavor', 1, '오늘의 비밀 암호를 하나 정해줘!', ARRAY['암호','비밀','재미','콘셉트']::text[], 'seed_c5b624905a1727a1'),
  ('maid', 'roleplay_flavor', 1, '카페에 유령이 산다면 어떤 유령일까?', ARRAY['유령','상상','귀여움','카페']::text[], 'seed_73a551653ef8abd9'),
  ('maid', 'roleplay_flavor', 1, '메이드 카드게임이 있다면 자기 카드의 능력치는?', ARRAY['카드','능력치','게임','자기표현']::text[], 'seed_f7d00240165941e0'),
  ('maid', 'roleplay_flavor', 1, '마법의 거울에 비친 오늘의 자기 모습은?', ARRAY['거울','마법','자기표현','상상']::text[], 'seed_fbd182a45a468552'),
  ('maid', 'roleplay_flavor', 1, '카페의 수호신이 있다면 어떤 모습일까?', ARRAY['수호신','상상','카페','판타지']::text[], 'seed_ce16c3538f25100b'),
  ('maid', 'roleplay_flavor', 1, '오늘 만든 음료에 이름을 붙인다면?', ARRAY['이름','음료','창의','카페']::text[], 'seed_f3a72511f10c0500'),
  ('maid', 'roleplay_flavor', 1, '자기만의 마법 지팡이가 있다면 어떤 모양?', ARRAY['지팡이','마법','디자인','상상']::text[], 'seed_1e5984e98cdd93e1'),
  ('maid', 'roleplay_flavor', 1, '오늘 카페에 한 가지 마법을 걸 수 있다면?', ARRAY['마법','카페','상상','효과']::text[], 'seed_cf707080a97558ec'),
  ('maid', 'roleplay_flavor', 1, '메이드 왕국이 있다면 자기 직위는?', ARRAY['왕국','직위','상상','콘셉트']::text[], 'seed_509ce4998905bfad'),
  ('maid', 'roleplay_flavor', 1, '카페 메뉴판이 주문서(스펠북)라면 어떤 디자인?', ARRAY['메뉴판','디자인','판타지','상상']::text[], 'seed_7718b674bde264b2'),
  ('maid', 'roleplay_flavor', 1, '오늘의 필살기를 하나 만든다면 이름은?', ARRAY['필살기','이름','게임','재미']::text[], 'seed_cc0bd5544968b1a3'),
  ('maid', 'roleplay_flavor', 1, '손님에게 거는 ''미소 마법''의 레벨은 1~10 중?', ARRAY['미소','마법','레벨','재미']::text[], 'seed_c5bc2de31cfb6d07'),
  ('maid', 'roleplay_flavor', 2, '카페가 이세계에 있다면 어떤 세계관이 어울릴까?', ARRAY['이세계','세계관','상상','카페']::text[], 'seed_74daed301ac2f989'),
  ('maid', 'roleplay_flavor', 2, '메이드 캐릭터의 배경 설정을 만든다면 어떤 스토리?', ARRAY['캐릭터','배경','스토리','창작']::text[], 'seed_6293e33e71eaaf02'),
  ('maid', 'roleplay_flavor', 2, '카페가 RPG 던전이라면 보스는 누구(무엇)?', ARRAY['RPG','던전','보스','상상']::text[], 'seed_69ed3d796c7edc42'),
  ('maid', 'roleplay_flavor', 2, '마법의 레시피북에 추가할 신메뉴와 그 마법 효과는?', ARRAY['레시피','마법','신메뉴','창의']::text[], 'seed_7de2c89ce7de912c'),
  ('maid', 'roleplay_flavor', 2, '메이드 팀으로 히어로 그룹을 만든다면 팀명과 역할은?', ARRAY['히어로','팀','역할','상상']::text[], 'seed_51ba922cfe6c75df'),
  ('maid', 'roleplay_flavor', 2, '카페 손님이 모두 판타지 종족이라면 어떤 종족이 올까?', ARRAY['판타지','종족','손님','상상']::text[], 'seed_1b65e10395e57215'),
  ('maid', 'roleplay_flavor', 2, '메이드 카페 뮤지컬을 만든다면 오프닝 넘버 제목은?', ARRAY['뮤지컬','제목','음악','창의']::text[], 'seed_8cecb781d48fcf06'),
  ('maid', 'roleplay_flavor', 2, '카페가 우주 정거장이라면 오늘의 미션은?', ARRAY['우주','미션','SF','상상']::text[], 'seed_3f10a0618e95fc9c'),
  ('maid', 'roleplay_flavor', 2, '마법의 재료로 ''행복 포션''을 만든다면 레시피는?', ARRAY['포션','레시피','마법','창의']::text[], 'seed_3a388899fe211909'),
  ('maid', 'roleplay_flavor', 2, '카페가 도서관이라면 추천 도서 한 권은?', ARRAY['도서관','추천','책','상상']::text[], 'seed_5bcae965b6f4785b'),
  ('maid', 'roleplay_flavor', 2, '메이드 전사로서 오늘 맞서야 할 적은?', ARRAY['전사','적','배틀','상상']::text[], 'seed_eefd6e8b39ae6725'),
  ('maid', 'roleplay_flavor', 2, '카페를 아이돌 그룹처럼 유닛으로 나눈다면?', ARRAY['유닛','아이돌','팀','상상']::text[], 'seed_76f37bb3d7d52b19'),
  ('maid', 'roleplay_flavor', 2, '타임머신으로 카페를 한 시대로 보낸다면 어느 시대?', ARRAY['타임머신','시대','상상','역사']::text[], 'seed_012aa658b8a91074'),
  ('maid', 'roleplay_flavor', 2, '카페 안에 비밀 방이 하나 더 있다면 어떤 용도?', ARRAY['비밀방','용도','상상','카페']::text[], 'seed_d1c95919cc79e256'),
  ('maid', 'roleplay_flavor', 2, '메이드 버전 자기소개를 RPG 캐릭터 소개처럼 해준다면?', ARRAY['RPG','캐릭터소개','자기표현','재미']::text[], 'seed_8517ab34d49fd871'),
  ('maid', 'roleplay_flavor', 2, '카페 OST 앨범을 만든다면 첫 번째 트랙 제목은?', ARRAY['OST','앨범','음악','창의']::text[], 'seed_48a48a962a20d6a2'),
  ('maid', 'roleplay_flavor', 2, '마법 학교에서 메이드 과목이 있다면 시험 문제는?', ARRAY['마법학교','시험','재미','상상']::text[], 'seed_059328c4f1c04e36'),
  ('maid', 'roleplay_flavor', 2, '카페가 해적선이라면 자기 해적 이름과 포지션은?', ARRAY['해적','이름','포지션','상상']::text[], 'seed_8279db0b981ad564'),
  ('maid', 'roleplay_flavor', 2, '메이드 카페 만화를 그린다면 제1화 제목과 내용은?', ARRAY['만화','제1화','스토리','창작']::text[], 'seed_b36ed9d9787cb6cf'),
  ('maid', 'roleplay_flavor', 2, '요일별 메이드 변신 콘셉트를 정해본다면?', ARRAY['요일','변신','콘셉트','시리즈']::text[], 'seed_179bd6e1755d8551'),
  ('maid', 'roleplay_flavor', 2, '카페 마스코트의 이름, 성격, 특기를 만들어줘!', ARRAY['마스코트','캐릭터','창작','카페']::text[], 'seed_1d620b467ebb1a1a'),
  ('maid', 'roleplay_flavor', 2, '메이드 콘셉트 사진집을 만든다면 테마는?', ARRAY['사진집','테마','콘셉트','창의']::text[], 'seed_19b03569e5c397bb'),
  ('maid', 'roleplay_flavor', 2, '카페에 계절별 한정 마법이 있다면 봄 마법은?', ARRAY['계절','마법','봄','상상']::text[], 'seed_32ab59adb494cff6'),
  ('maid', 'roleplay_flavor', 2, '메이드 카페 보드게임을 만든다면 어떤 규칙?', ARRAY['보드게임','규칙','게임','창의']::text[], 'seed_c186dbe848bcbe0c'),
  ('maid', 'roleplay_flavor', 2, '카페가 동화 속 세계라면 지금은 어떤 동화?', ARRAY['동화','세계','상상','콘셉트']::text[], 'seed_a880f6ff6265403a'),
  ('maid', 'roleplay_flavor', 3, '메이드 카페를 테마로 단편소설을 쓴다면 첫 문장과 마지막 문장은?', ARRAY['소설','첫문장','창작','스토리']::text[], 'seed_72fe7a0372b93187'),
  ('maid', 'roleplay_flavor', 3, '카페가 다차원 포탈이라면, 이 카페에서만 가능한 특별한 경험은?', ARRAY['다차원','포탈','특별','상상']::text[], 'seed_3d7917c75197e022'),
  ('maid', 'roleplay_flavor', 3, '자기만의 메이드 세계관을 하나 만들어 본다면? (설정/규칙/주인공)', ARRAY['세계관','설정','창작','깊이']::text[], 'seed_cbd3e60f60f088d2'),
  ('maid', 'roleplay_flavor', 3, '메이드 카페의 역사를 100년 후의 사람에게 설명하는 다큐멘터리를 만든다면?', ARRAY['다큐','100년후','문화','역사']::text[], 'seed_63828671aa8e19ca'),
  ('maid', 'roleplay_flavor', 3, '카페가 마법학원이라면 자기가 가르치는 수업의 커리큘럼은?', ARRAY['학원','수업','커리큘럼','상상']::text[], 'seed_d9be99a9cd05fcef'),
  ('maid', 'roleplay_flavor', 3, '메이드 카페를 배경으로 한 게임의 엔딩 시나리오를 만들어 본다면?', ARRAY['게임','엔딩','시나리오','창작']::text[], 'seed_00f5bd59d4420cf2'),
  ('maid', 'roleplay_flavor', 3, '카페의 사계절을 각각 하나의 캐릭터로 의인화한다면?', ARRAY['사계절','의인화','캐릭터','창의']::text[], 'seed_a301dbdc835c5ff2'),
  ('maid', 'roleplay_flavor', 3, '메이드 문화를 주제로 전시회를 연다면 섹션 구성은?', ARRAY['전시회','섹션','문화','기획']::text[], 'seed_d320f3eb01b3978b'),
  ('maid', 'roleplay_flavor', 3, '카페가 마법의 나라의 대사관이라면 어떤 외교를 할까?', ARRAY['대사관','외교','마법나라','상상']::text[], 'seed_eca3d22ddc09e814'),
  ('maid', 'roleplay_flavor', 3, '메이드 카페 유니버스의 빌런은 누구이고 어떻게 물리칠까?', ARRAY['빌런','유니버스','배틀','스토리']::text[], 'seed_a5c7534e98291925'),
  ('maid', 'roleplay_flavor', 3, '카페의 모든 메뉴에 마법 스토리를 붙인다면 시그니처 메뉴의 전설은?', ARRAY['전설','메뉴','스토리','세계관']::text[], 'seed_167cb766b0c43b29'),
  ('maid', 'roleplay_flavor', 3, '메이드 카페 주제의 뮤지컬 대본 핵심 장면을 하나 만들어 본다면?', ARRAY['뮤지컬','장면','대본','창작']::text[], 'seed_340be18fec21ae32'),
  ('maid', 'roleplay_flavor', 3, '카페가 다른 차원과 연결된 게이트라면, 다른 차원의 메이드는 어떤 모습?', ARRAY['다른차원','메이드','상상','SF']::text[], 'seed_870ebb122cedd518'),
  ('maid', 'roleplay_flavor', 3, '자기를 주인공으로 한 메이드 애니메이션의 오프닝 영상을 묘사해본다면?', ARRAY['애니','오프닝','묘사','창작']::text[], 'seed_7cf889ccc96242c4'),
  ('maid', 'roleplay_flavor', 3, '카페 100주년 기념 타임캡슐에 넣을 세 가지와 미래에 보내는 메시지는?', ARRAY['타임캡슐','미래','메시지','기념']::text[], 'seed_010eeee64499a5c5'),
  ('maid', 'deep_but_safe', 1, '요즘 가장 감사하게 느끼는 것 하나는?', ARRAY['감사','감정','가벼운']::text[], 'seed_f1c9b414796bafc5'),
  ('maid', 'deep_but_safe', 1, '스트레스 풀 때 하는 일은?', ARRAY['스트레스','해소','일상']::text[], 'seed_fd71399790300c93'),
  ('maid', 'deep_but_safe', 1, '요즘 가장 행복한 순간은?', ARRAY['행복','순간','일상']::text[], 'seed_feda596bde7dd5e8'),
  ('maid', 'deep_but_safe', 1, '자기 자신에게 해주고 싶은 칭찬 한마디?', ARRAY['칭찬','자기','긍정']::text[], 'seed_bb72a605a1cc4e8d'),
  ('maid', 'deep_but_safe', 1, '최근에 감동받은 작은 일은?', ARRAY['감동','작은일','일상']::text[], 'seed_4491d775c7636179'),
  ('maid', 'deep_but_safe', 1, '좋아하는 명언이나 좌우명이 있어?', ARRAY['명언','좌우명','가치관']::text[], 'seed_aa29370a80af56cd'),
  ('maid', 'deep_but_safe', 1, '혼자만의 시간에 주로 뭘 해?', ARRAY['혼자','시간','취미']::text[], 'seed_9dcadd4e670b840b'),
  ('maid', 'deep_but_safe', 1, '요즘 가장 듣고 싶은 말은?', ARRAY['듣고싶은말','감정','소통']::text[], 'seed_f3ee2e26bfffb3a2'),
  ('maid', 'deep_but_safe', 1, '자기한테 가장 소중한 물건은?', ARRAY['소중','물건','애착']::text[], 'seed_6238c38ce25bdc90'),
  ('maid', 'deep_but_safe', 1, '최근에 용기 낸 일이 있어?', ARRAY['용기','도전','경험']::text[], 'seed_d0f2e8ea99d420cf'),
  ('maid', 'deep_but_safe', 1, '지금 가장 응원하고 싶은 사람은?', ARRAY['응원','사람','관계']::text[], 'seed_704b76fe11f9b557'),
  ('maid', 'deep_but_safe', 1, '자기를 한 단어로 표현하면?', ARRAY['자기표현','한단어','정체성']::text[], 'seed_1d865485810c5460'),
  ('maid', 'deep_but_safe', 1, '요즘 가장 많이 하는 고민은? (가볍게)', ARRAY['고민','요즘','가벼운']::text[], 'seed_58cb9f45a172a80a'),
  ('maid', 'deep_but_safe', 1, '행복할 때 무의식적으로 하는 행동이 있어?', ARRAY['행복','습관','무의식']::text[], 'seed_89a047452f94e045'),
  ('maid', 'deep_but_safe', 1, '자기한테 가장 잘 맞는 색깔은?', ARRAY['색깔','자기표현','취향']::text[], 'seed_7deccad764324c17'),
  ('maid', 'deep_but_safe', 1, '요즘 마음이 따뜻해지는 노래는?', ARRAY['노래','따뜻','감성']::text[], 'seed_bd2b8d8c94c60deb'),
  ('maid', 'deep_but_safe', 1, '가장 편안하게 느끼는 장소는?', ARRAY['장소','편안','쉼']::text[], 'seed_92c21f425a726bf2'),
  ('maid', 'deep_but_safe', 1, '요즘 읽고 있는 책이나 보고 있는 작품은?', ARRAY['책','작품','취미']::text[], 'seed_04232d8e4e4f1d95'),
  ('maid', 'deep_but_safe', 1, '자기한테 가장 잘 맞는 계절은?', ARRAY['계절','성격','취향']::text[], 'seed_3d8749a4b3169dd9'),
  ('maid', 'deep_but_safe', 1, '최근에 새로 도전해본 것이 있어?', ARRAY['도전','새로움','경험']::text[], 'seed_80a8832be8cc9253'),
  ('maid', 'deep_but_safe', 1, '자기를 꽃에 비유하면 뭘까?', ARRAY['꽃','비유','자기표현']::text[], 'seed_a5e61a11319dfbf1'),
  ('maid', 'deep_but_safe', 1, '요즘 가장 기대하는 일은?', ARRAY['기대','미래','긍정']::text[], 'seed_4ab4bb2dc505ad27'),
  ('maid', 'deep_but_safe', 1, '자기가 생각하는 ''작은 사치''는?', ARRAY['사치','작은행복','취향']::text[], 'seed_dadd71c465078590'),
  ('maid', 'deep_but_safe', 1, '가장 좋아하는 시간대는?', ARRAY['시간대','취향','일상']::text[], 'seed_122e19ac19b603d2'),
  ('maid', 'deep_but_safe', 1, '요즘 자기에게 가장 필요한 건?', ARRAY['필요','자기관리','현재']::text[], 'seed_6fb0619307b6a871'),
  ('maid', 'deep_but_safe', 1, '자기 인생의 BGM을 정한다면?', ARRAY['BGM','인생','음악']::text[], 'seed_076b45fa6a53e572'),
  ('maid', 'deep_but_safe', 1, '가장 마지막으로 울었던 이유는? (가볍게)', ARRAY['울음','감정','솔직']::text[], 'seed_341719f7175a3641'),
  ('maid', 'deep_but_safe', 1, '하루 중 가장 ''나다운'' 시간은?', ARRAY['나다운','시간','정체성']::text[], 'seed_c3242bc5346eb77d'),
  ('maid', 'deep_but_safe', 1, '자기한테 주고 싶은 선물은?', ARRAY['선물','자기','위로']::text[], 'seed_2990eaac3517f76c'),
  ('maid', 'deep_but_safe', 1, '요즘 가장 편하게 지내는 사람은?', ARRAY['편한사람','관계','일상']::text[], 'seed_3f190dbe4839bcc6'),
  ('maid', 'deep_but_safe', 1, '자기만의 힐링 방법이 있어?', ARRAY['힐링','방법','자기관리']::text[], 'seed_43c33e8c4739d5c8'),
  ('maid', 'deep_but_safe', 1, '최근에 자기 자신이 대견했던 순간은?', ARRAY['대견','성취','긍정']::text[], 'seed_d10f024cfd70a04d'),
  ('maid', 'deep_but_safe', 1, '가장 좋아하는 냄새는?', ARRAY['냄새','감각','취향']::text[], 'seed_2500188f82482c07'),
  ('maid', 'deep_but_safe', 1, '지금 마음의 날씨는?', ARRAY['마음','날씨','감정']::text[], 'seed_c5634f6d342f7c45'),
  ('maid', 'deep_but_safe', 1, '요즘 자주 생각나는 추억이 있어?', ARRAY['추억','기억','감성']::text[], 'seed_c3d1d62dee15fede'),
  ('maid', 'deep_but_safe', 1, '자기한테 가장 맞는 동물은?', ARRAY['동물','자기표현','성격']::text[], 'seed_b90d3f910e87c7af'),
  ('maid', 'deep_but_safe', 1, '오늘 하루를 한마디로 요약하면?', ARRAY['요약','하루','한마디']::text[], 'seed_33bc02aab2dd283d'),
  ('maid', 'deep_but_safe', 1, '자기만의 행운의 숫자가 있어?', ARRAY['숫자','행운','개인']::text[], 'seed_eb7f68f9581f897d'),
  ('maid', 'deep_but_safe', 1, '요즘 감사 인사를 하고 싶은 사람은?', ARRAY['감사','인사','관계']::text[], 'seed_13ae890c47ecf3d2'),
  ('maid', 'deep_but_safe', 1, '자기가 가장 좋아하는 자기 장점은?', ARRAY['장점','긍정','자기평가']::text[], 'seed_61f162db67f12423'),
  ('maid', 'deep_but_safe', 2, '일과 자기 자신 사이에서 밸런스를 유지하는 비결은?', ARRAY['밸런스','일','자기관리','비결']::text[], 'seed_2c7d6e8478361d0d'),
  ('maid', 'deep_but_safe', 2, '가장 힘들었을 때 자기를 지탱해준 것은?', ARRAY['힘듦','지탱','극복','감사']::text[], 'seed_d3d617dbf1994ddc'),
  ('maid', 'deep_but_safe', 2, '자기 인생에서 터닝포인트라고 생각하는 순간은?', ARRAY['터닝포인트','인생','변화','성장']::text[], 'seed_420ff431d25d5eb4'),
  ('maid', 'deep_but_safe', 2, '5년 전의 자기와 지금의 자기, 가장 달라진 점은?', ARRAY['변화','5년전','성장','비교']::text[], 'seed_894d57cc92da8915'),
  ('maid', 'deep_but_safe', 2, '자기가 소중히 여기는 ''관계의 규칙''이 있다면?', ARRAY['관계','규칙','가치관','소통']::text[], 'seed_04c9f02b7262ac95'),
  ('maid', 'deep_but_safe', 2, '가장 영향을 많이 준 사람(실명 없이)은 어떤 사람이야?', ARRAY['영향','사람','성장','가치관']::text[], 'seed_330a43789a0ce497'),
  ('maid', 'deep_but_safe', 2, '자기가 되고 싶은 ''어른''의 모습은?', ARRAY['미래','이상','어른','가치관']::text[], 'seed_a9ed90a462b3f192'),
  ('maid', 'deep_but_safe', 2, '포기하고 싶었지만 포기하지 않은 경험이 있다면?', ARRAY['포기','인내','경험','성장']::text[], 'seed_5c92af68c7c74783'),
  ('maid', 'deep_but_safe', 2, '자기가 생각하는 ''진짜 강한 사람''은 어떤 사람이야?', ARRAY['강함','가치관','사람','철학']::text[], 'seed_f7e4b2c32f9a54d0'),
  ('maid', 'deep_but_safe', 2, '일하면서 배운 ''사람 대하는 법'' 중 가장 중요한 건?', ARRAY['소통','배움','일','관계']::text[], 'seed_03b5536b86448f1e'),
  ('maid', 'deep_but_safe', 2, '자기에게 ''성공''이란 어떤 의미야?', ARRAY['성공','정의','가치관','철학']::text[], 'seed_914e03720b40a123'),
  ('maid', 'deep_but_safe', 2, '가장 후회하는 것과 가장 잘한 것, 각각 하나씩?', ARRAY['후회','잘한일','회고','솔직']::text[], 'seed_1daedaaf91b56e1b'),
  ('maid', 'deep_but_safe', 2, '외로울 때 자기만의 대처법은?', ARRAY['외로움','대처','자기관리','방법']::text[], 'seed_5b9be583b556c172'),
  ('maid', 'deep_but_safe', 2, '자기가 생각하는 ''좋은 인간관계''의 조건은?', ARRAY['인간관계','조건','가치관','소통']::text[], 'seed_ec6f43440c029f6d'),
  ('maid', 'deep_but_safe', 2, '지금의 자기에게 가장 큰 도전은 뭐야?', ARRAY['도전','현재','성장','목표']::text[], 'seed_8b09b1a761bafa8a'),
  ('maid', 'deep_but_safe', 2, '자기만의 ''마음 리셋'' 방법이 있어?', ARRAY['리셋','마음','자기관리','방법']::text[], 'seed_a4d1b4b92aa47d37'),
  ('maid', 'deep_but_safe', 2, '가장 기억에 남는 선물(받은 것 또는 준 것)은?', ARRAY['선물','기억','감동','관계']::text[], 'seed_223ed951a22438da'),
  ('maid', 'deep_but_safe', 2, '자기 인생의 모토를 새로 만든다면?', ARRAY['모토','인생','가치관','창의']::text[], 'seed_b6891a1b4c833a99'),
  ('maid', 'deep_but_safe', 2, '누군가에게 용기를 주고 싶다면 어떤 말을 할래?', ARRAY['용기','응원','메시지','따뜻']::text[], 'seed_bc7c7fc91d51388c'),
  ('maid', 'deep_but_safe', 2, '자기가 가장 자신 없는 부분과 그걸 극복하려는 노력은?', ARRAY['약점','극복','솔직','성장']::text[], 'seed_43993ba237501efe'),
  ('maid', 'deep_but_safe', 2, '10년 후의 자기에게 보내는 편지 한 줄은?', ARRAY['편지','미래','한줄','감성']::text[], 'seed_cf5421c1d2dbaf5f'),
  ('maid', 'deep_but_safe', 2, '자기가 가장 편안하게 느끼는 사람의 특징은?', ARRAY['편안','사람','특징','관계']::text[], 'seed_ca7f112e86a9e619'),
  ('maid', 'deep_but_safe', 2, '꿈에서라도 하고 싶은 일이 있다면?', ARRAY['꿈','소원','상상','자유']::text[], 'seed_502b9e3b81eaee0c'),
  ('maid', 'deep_but_safe', 2, '자기에게 ''쉼''이란 어떤 의미야?', ARRAY['쉼','정의','가치관','자기관리']::text[], 'seed_fda7595d2263decf'),
  ('maid', 'deep_but_safe', 2, '가장 기억에 남는 팬(손님)과의 대화 주제는?', ARRAY['대화','팬','기억','소통']::text[], 'seed_8a08a2669e0ad9d5'),
  ('maid', 'deep_but_safe', 3, '자기 인생에서 가장 큰 ''전환점''은 무엇이었고, 그게 지금의 자기를 어떻게 만들었어?', ARRAY['전환점','인생','성장','깊이']::text[], 'seed_b18213bfada8a146'),
  ('maid', 'deep_but_safe', 3, '사람들이 자기에 대해 모르는, 하지만 알아줬으면 하는 부분이 있다면?', ARRAY['알아줬으면','솔직','정체성','소통']::text[], 'seed_817643bb8dc36a9e'),
  ('maid', 'deep_but_safe', 3, '자기가 세상에 남기고 싶은 것 하나는?', ARRAY['유산','가치','세상','철학']::text[], 'seed_b7271e4ab4911af6'),
  ('maid', 'deep_but_safe', 3, '가장 두려운 것과 그 두려움에 어떻게 대처하고 있는지?', ARRAY['두려움','대처','솔직','용기']::text[], 'seed_e0e0cdf96df9c466'),
  ('maid', 'deep_but_safe', 3, '''행복''이란 무엇인지, 자기만의 정의를 내린다면?', ARRAY['행복','정의','철학','가치관']::text[], 'seed_2f1227825cb50bf5'),
  ('maid', 'deep_but_safe', 3, '지금까지 살면서 가장 큰 깨달음은 뭐였어?', ARRAY['깨달음','인생','지혜','경험']::text[], 'seed_20b481f122071f93'),
  ('maid', 'deep_but_safe', 3, '자기 인생을 영화로 만든다면 어떤 장르이고, 지금은 어떤 장면?', ARRAY['영화','장르','인생','창의']::text[], 'seed_2233d9482568be4a'),
  ('maid', 'deep_but_safe', 3, '가장 존경하는 사람(실명 없이)의 어떤 점을 존경해?', ARRAY['존경','사람','가치관','배움']::text[], 'seed_7387b778a05ef7bf'),
  ('maid', 'deep_but_safe', 3, '''나''라는 사람의 설명서를 쓴다면 어떤 내용이 들어갈까?', ARRAY['설명서','자기','정체성','창의']::text[], 'seed_e286f3da1d7d726e'),
  ('maid', 'deep_but_safe', 3, '세상에 하나만 바꿀 수 있다면 무엇을 바꾸고 싶어?', ARRAY['세상','변화','가치관','소원']::text[], 'seed_53201ff545ec2a6b'),
  ('maid', 'deep_but_safe', 3, '자기가 생각하는 ''진짜 어른이 되는 것''의 의미는?', ARRAY['어른','의미','성장','철학']::text[], 'seed_865e6a440710779c'),
  ('maid', 'deep_but_safe', 3, '지금의 자기를 한 편의 시로 표현한다면?', ARRAY['시','자기표현','창의','감성']::text[], 'seed_c68da463c5ab7bfd'),
  ('maid', 'deep_but_safe', 3, '자기 인생에서 가장 ''용기 있었던 순간''과 그 결과는?', ARRAY['용기','순간','결과','경험']::text[], 'seed_adc4df4ef0244693'),
  ('maid', 'deep_but_safe', 3, '만약 과거의 자기에게 딱 한 가지 충고를 할 수 있다면?', ARRAY['과거','충고','시간','지혜']::text[], 'seed_e636544218a5a2e7'),
  ('maid', 'deep_but_safe', 3, '자기 삶에서 가장 아름다운 순간은 언제였어?', ARRAY['아름다운','순간','인생','감성']::text[], 'seed_6a7e0d1666dbeeb2'),
  ('ex_idol', 'icebreaker', 1, '오늘 기분을 노래 제목으로 표현하면?', ARRAY['기분','노래','가벼운']::text[], 'seed_48dde4dd354c3272'),
  ('ex_idol', 'icebreaker', 1, '지금 듣고 있는 음악은?', ARRAY['음악','현재','취향']::text[], 'seed_595cd059f42cd9f0'),
  ('ex_idol', 'icebreaker', 1, '오늘 아침에 먹은 건?', ARRAY['아침','음식','일상']::text[], 'seed_0d929b6b017bc566'),
  ('ex_idol', 'icebreaker', 1, '요즘 빠져 있는 취미는?', ARRAY['취미','요즘','관심사']::text[], 'seed_ed38758ed4cb9697'),
  ('ex_idol', 'icebreaker', 1, '지금 신고 있는 신발은?', ARRAY['신발','패션','디테일']::text[], 'seed_e3fa4a8af8e1f57c'),
  ('ex_idol', 'icebreaker', 1, '오늘 컨디션을 별점으로 매기면? (5점 만점)', ARRAY['컨디션','별점','가벼운']::text[], 'seed_7af4fa8aee89938e'),
  ('ex_idol', 'icebreaker', 1, '요즘 자주 가는 편의점 간식은?', ARRAY['간식','편의점','취향']::text[], 'seed_fd7d2011a5f43d2e'),
  ('ex_idol', 'icebreaker', 1, '마지막으로 본 영상(유튜브/틱톡 등)은?', ARRAY['영상','SNS','일상']::text[], 'seed_1444e1b5a9e5d08c'),
  ('ex_idol', 'icebreaker', 1, '좋아하는 라면 종류는?', ARRAY['라면','음식','선택']::text[], 'seed_1e48e1cad7f1b55f'),
  ('ex_idol', 'icebreaker', 1, '오늘 하늘 봤어?', ARRAY['하늘','일상','가벼운']::text[], 'seed_25f5fccbc96f02c1'),
  ('ex_idol', 'icebreaker', 1, '아이돌 시절 습관 중 아직도 남아있는 건?', ARRAY['습관','아이돌','과거']::text[], 'seed_efda15b20e58e879'),
  ('ex_idol', 'icebreaker', 1, '커피 vs 차?', ARRAY['음료','선택','취향']::text[], 'seed_1a201576f89fa95a'),
  ('ex_idol', 'icebreaker', 1, '요즘 가장 많이 쓰는 앱은?', ARRAY['앱','디지털','일상']::text[], 'seed_ce51ffd18523a4b5'),
  ('ex_idol', 'icebreaker', 1, '오늘 거울 몇 번 봤어?', ARRAY['거울','습관','재미']::text[], 'seed_8c0f7cbb49c8fffa'),
  ('ex_idol', 'icebreaker', 1, '지금 머릿속에 있는 단어 하나는?', ARRAY['단어','현재','자유']::text[], 'seed_7e69d0411e3750de'),
  ('ex_idol', 'icebreaker', 1, '요즘 잠은 잘 자고 있어?', ARRAY['수면','건강','일상']::text[], 'seed_1d82c56174369294'),
  ('ex_idol', 'icebreaker', 1, '가장 최근에 웃은 이유는?', ARRAY['웃음','이유','일상']::text[], 'seed_cdc39f2447a73716'),
  ('ex_idol', 'icebreaker', 1, '핸드폰 배경화면은 뭐야?', ARRAY['배경화면','취향','디지털']::text[], 'seed_a1d35431a16f247f'),
  ('ex_idol', 'icebreaker', 1, '요즘 즐겨 보는 드라마나 예능은?', ARRAY['드라마','예능','취향']::text[], 'seed_0ff3d2f027e8a164'),
  ('ex_idol', 'icebreaker', 1, '아침형 인간? 올빼미형?', ARRAY['성향','선택','일상']::text[], 'seed_880c4542632f045a'),
  ('ex_idol', 'icebreaker', 1, '오늘 가장 많이 한 행동은?', ARRAY['행동','오늘','일상']::text[], 'seed_6f515aa6a7f90b3f'),
  ('ex_idol', 'icebreaker', 1, '지금 입고 있는 옷 색깔은?', ARRAY['옷','색깔','패션']::text[], 'seed_584897ced46af996'),
  ('ex_idol', 'icebreaker', 1, '요즘 가장 자주 연락하는 사람은?', ARRAY['연락','사람','관계']::text[], 'seed_2a520f1000df754e'),
  ('ex_idol', 'icebreaker', 1, '좋아하는 날씨는?', ARRAY['날씨','취향','가벼운']::text[], 'seed_849974ddfd6ddb12'),
  ('ex_idol', 'icebreaker', 1, '지금 가장 먹고 싶은 음식은?', ARRAY['음식','욕구','현재']::text[], 'seed_32741fd121cacd1e'),
  ('ex_idol', 'icebreaker', 1, '마지막으로 사진 찍은 건 뭐야?', ARRAY['사진','최근','일상']::text[], 'seed_d0c8b6942f880c1c'),
  ('ex_idol', 'icebreaker', 1, '요즘 뭐에 돈을 제일 많이 써?', ARRAY['소비','요즘','일상']::text[], 'seed_cafd3f819a4ec546'),
  ('ex_idol', 'icebreaker', 1, '좋아하는 숫자가 있어?', ARRAY['숫자','취향','개인']::text[], 'seed_a047d76be956fe6f'),
  ('ex_idol', 'icebreaker', 1, '오늘 가장 먼저 한 일은?', ARRAY['아침','루틴','일상']::text[], 'seed_9bec7ef2920c0cc3'),
  ('ex_idol', 'icebreaker', 1, '지금 기분을 음식으로 표현하면?', ARRAY['기분','음식','비유']::text[], 'seed_09b904b6b5600b1a'),
  ('ex_idol', 'icebreaker', 1, '요즘 플레이리스트에 새로 추가한 노래는?', ARRAY['노래','플레이리스트','음악']::text[], 'seed_9f0ea63206ac2b1b'),
  ('ex_idol', 'icebreaker', 1, '바다 vs 산?', ARRAY['선택','자연','취향']::text[], 'seed_0a4cfe70678861c4'),
  ('ex_idol', 'icebreaker', 1, '오늘 한 운동이 있어?', ARRAY['운동','건강','일상']::text[], 'seed_29c727b2b54e012f'),
  ('ex_idol', 'icebreaker', 1, '지금 창밖 풍경은 어때?', ARRAY['풍경','현재','환경']::text[], 'seed_d81cb845f69c16d6'),
  ('ex_idol', 'icebreaker', 1, '최근에 받은 택배는 뭐야?', ARRAY['택배','쇼핑','일상']::text[], 'seed_dff70c57cd3d6942'),
  ('ex_idol', 'icebreaker', 1, '아이돌 시절 별명이 있었어?', ARRAY['별명','아이돌','과거']::text[], 'seed_de7da5a4f8599b58'),
  ('ex_idol', 'icebreaker', 1, '오늘 하루를 한 글자로 표현하면?', ARRAY['한글자','하루','표현']::text[], 'seed_18620ddf76454437'),
  ('ex_idol', 'icebreaker', 1, '가장 좋아하는 색 조합은?', ARRAY['색조합','취향','디자인']::text[], 'seed_49e1714745df2bb0'),
  ('ex_idol', 'icebreaker', 1, '지금 가방 안에 뭐가 들어있어?', ARRAY['가방','소지품','일상']::text[], 'seed_edb00aa94bd6629a'),
  ('ex_idol', 'icebreaker', 1, '요즘 가장 기대하는 것 하나는?', ARRAY['기대','긍정','요즘']::text[], 'seed_524d60104dc8d3f0'),
  ('ex_idol', 'icebreaker', 2, '아이돌 활동을 시작하게 된 계기가 뭐야?', ARRAY['계기','시작','아이돌','스토리']::text[], 'seed_fd82baeb87cc2e56'),
  ('ex_idol', 'icebreaker', 2, '활동 시절 가장 좋아했던 무대 의상은?', ARRAY['의상','무대','아이돌','취향']::text[], 'seed_51c75fe020f8fe7c'),
  ('ex_idol', 'icebreaker', 2, '연습생 시절의 하루 일과는 어땠어?', ARRAY['연습생','일과','과거','일상']::text[], 'seed_b1c5a7a574b1d812'),
  ('ex_idol', 'icebreaker', 2, '아이돌 활동 후 일상에서 가장 달라진 점은?', ARRAY['변화','일상','전후','비교']::text[], 'seed_abad80b1a6d4e026'),
  ('ex_idol', 'icebreaker', 2, '무대에서 가장 좋아했던 포지션(센터/메인보컬 등)은?', ARRAY['포지션','무대','아이돌','취향']::text[], 'seed_d8a2ec3de3f40627'),
  ('ex_idol', 'icebreaker', 2, '연습할 때 가장 많이 들었던 장르의 음악은?', ARRAY['연습','음악','장르','아이돌']::text[], 'seed_aa143262e8ed6874'),
  ('ex_idol', 'icebreaker', 2, '활동 시절 팬에게 받은 것 중 가장 기억에 남는 건?', ARRAY['팬','선물','기억','감동']::text[], 'seed_d0f1c66f3a23049e'),
  ('ex_idol', 'icebreaker', 2, '지금 다시 무대에 선다면 어떤 노래를 부르고 싶어?', ARRAY['무대','노래','상상','아이돌']::text[], 'seed_cbb429180842818e'),
  ('ex_idol', 'icebreaker', 2, '활동 시절 가장 긴장됐던 무대는?', ARRAY['긴장','무대','에피소드','아이돌']::text[], 'seed_ff96f2786033729a'),
  ('ex_idol', 'icebreaker', 2, '쉬는 날에 주로 뭘 하면서 보냈어? (활동 당시)', ARRAY['휴일','활동시절','일상','과거']::text[], 'seed_07be88889196244d'),
  ('ex_idol', 'icebreaker', 2, '연습생 동기들과의 추억 중 하나를 들려줄 수 있어?', ARRAY['동기','추억','연습생','우정']::text[], 'seed_d5cdfbe617546cca'),
  ('ex_idol', 'icebreaker', 2, '아이돌 활동과 지금 생활의 공통점이 있다면?', ARRAY['공통점','현재','과거','비교']::text[], 'seed_b664e1ef95db1126'),
  ('ex_idol', 'icebreaker', 2, '가장 자신 있었던 퍼포먼스는?', ARRAY['퍼포먼스','자신감','아이돌','무대']::text[], 'seed_f9263284c4890a82'),
  ('ex_idol', 'icebreaker', 2, '활동 시절 먹방(식사) 에피소드가 있어?', ARRAY['먹방','식사','에피소드','과거']::text[], 'seed_5c39fd4256768bc5'),
  ('ex_idol', 'icebreaker', 2, '팬미팅에서 가장 기억에 남는 순간은?', ARRAY['팬미팅','기억','팬','순간']::text[], 'seed_686f7a9c09d724e5'),
  ('ex_idol', 'icebreaker', 2, '아이돌 시절 좋아했던 선배 아이돌은?', ARRAY['선배','롤모델','아이돌','취향']::text[], 'seed_e40e09fa2ecef506'),
  ('ex_idol', 'icebreaker', 2, '활동 중 웃긴 실수 에피소드가 있다면?', ARRAY['실수','웃김','에피소드','무대']::text[], 'seed_88eb92bd7283c820'),
  ('ex_idol', 'icebreaker', 2, '가장 많이 연습한 안무는 뭐였어?', ARRAY['안무','연습','노력','아이돌']::text[], 'seed_837a6fe252f5be6a'),
  ('ex_idol', 'icebreaker', 2, '활동 시절 자기만의 루틴이 있었어?', ARRAY['루틴','활동시절','습관','아이돌']::text[], 'seed_765011c11a5c060a'),
  ('ex_idol', 'icebreaker', 2, '요즘 음악 시장에서 주목하고 있는 건?', ARRAY['음악시장','트렌드','관심','현재']::text[], 'seed_9b2d0c3dabf8229b'),
  ('ex_idol', 'icebreaker', 2, '아이돌 활동 경험이 현재 어떤 면에서 도움이 돼?', ARRAY['경험','도움','현재','성장']::text[], 'seed_b24c2abaf93b17cd'),
  ('ex_idol', 'icebreaker', 2, '활동 당시 가장 좋아했던 연습실의 특징은?', ARRAY['연습실','공간','기억','아이돌']::text[], 'seed_1978ba8f0a10640d'),
  ('ex_idol', 'icebreaker', 2, '무대 전 긴장 풀기 위해 하던 행동은?', ARRAY['긴장풀기','루틴','무대','방법']::text[], 'seed_1830f15214444e39'),
  ('ex_idol', 'icebreaker', 2, '아이돌 시절 가장 많이 먹었던 음식은?', ARRAY['음식','아이돌','식사','과거']::text[], 'seed_5b19191358591cec'),
  ('ex_idol', 'icebreaker', 2, '활동 시절의 자기와 지금의 자기, 어떤 점이 같아?', ARRAY['같은점','과거','현재','비교']::text[], 'seed_21b6768a0d2caa88'),
  ('ex_idol', 'icebreaker', 3, '아이돌이라는 경험이 자기 정체성에 어떤 영향을 줬어?', ARRAY['정체성','영향','아이돌','성장']::text[], 'seed_29e1d7bf8cbaf2b9'),
  ('ex_idol', 'icebreaker', 3, '무대 위의 자기와 무대 아래의 자기, 어떤 관계야?', ARRAY['무대','자아','관계','정체성']::text[], 'seed_8899512062da1df4'),
  ('ex_idol', 'icebreaker', 3, '아이돌 활동을 그만둔 후 가장 크게 변한 가치관은?', ARRAY['가치관','변화','은퇴후','성장']::text[], 'seed_77ae9f000137d41d'),
  ('ex_idol', 'icebreaker', 3, '팬과의 관계에서 가장 중요하다고 생각하는 건?', ARRAY['팬','관계','가치','소통']::text[], 'seed_7debe9c377e23243'),
  ('ex_idol', 'icebreaker', 3, '아이돌 문화가 자기에게 남긴 가장 큰 선물은?', ARRAY['선물','아이돌','가치','감사']::text[], 'seed_07b5045dcb9d5b84'),
  ('ex_idol', 'icebreaker', 3, '다시 그 시절로 돌아갈 수 있다면, 한 가지 다르게 하고 싶은 건?', ARRAY['과거','다시','선택','회고']::text[], 'seed_20da715ba252c778'),
  ('ex_idol', 'icebreaker', 3, '아이돌 활동을 모르는 사람에게 그 세계를 설명한다면?', ARRAY['설명','아이돌','문화','외부']::text[], 'seed_c70272a59f3c1a4c'),
  ('ex_idol', 'icebreaker', 3, '''꿈을 쫓는다는 것''에 대해 자기 경험을 바탕으로 말해준다면?', ARRAY['꿈','경험','인사이트','가치']::text[], 'seed_8980ad16b99595a0'),
  ('ex_idol', 'icebreaker', 3, '지금의 자기에게 데뷔 직전의 자기가 해주고 싶은 말은?', ARRAY['데뷔','메시지','과거','성장']::text[], 'seed_fdd7cc147c3ab611'),
  ('ex_idol', 'icebreaker', 3, '아이돌 산업에 대해 바깥에서 모르는 긍정적인 면은?', ARRAY['산업','긍정','인사이트','문화']::text[], 'seed_5b6be9d9ac365edd'),
  ('ex_idol', 'icebreaker', 3, '활동을 마친 후 ''나는 누구인가''라는 질문에 어떻게 답했어?', ARRAY['정체성','질문','은퇴후','자아']::text[], 'seed_9c32316192adb616'),
  ('ex_idol', 'icebreaker', 3, '아이돌 경험이 인간관계에 어떤 영향을 줬어?', ARRAY['인간관계','영향','경험','변화']::text[], 'seed_255deb4db8b4575c'),
  ('ex_idol', 'icebreaker', 3, '무대에서의 마지막 순간(또는 가장 인상적인 순간)을 떠올린다면?', ARRAY['마지막','무대','기억','감정']::text[], 'seed_dea6b3ef62af97e3'),
  ('ex_idol', 'icebreaker', 3, '아이돌 이후의 삶에서 새롭게 발견한 자기 자신은?', ARRAY['발견','자기','새로운','성장']::text[], 'seed_4ea5f0583dc6c26a'),
  ('ex_idol', 'icebreaker', 3, '후배 아이돌에게 해주고 싶은 조언이 있다면?', ARRAY['조언','후배','아이돌','경험담']::text[], 'seed_b5659c3e2098ec0a'),
  ('ex_idol', 'daily_scene', 1, '오늘 아침 루틴은 어땠어?', ARRAY['아침','루틴','일상']::text[], 'seed_6c74921ab138ac89'),
  ('ex_idol', 'daily_scene', 1, '지금 있는 곳의 분위기는?', ARRAY['환경','현재','분위기']::text[], 'seed_49655f37a731618d'),
  ('ex_idol', 'daily_scene', 1, '오늘 점심 뭐 먹을 예정이야?', ARRAY['점심','음식','계획']::text[], 'seed_b60578dba67aeb30'),
  ('ex_idol', 'daily_scene', 1, '요즘 운동하고 있어?', ARRAY['운동','건강','일상']::text[], 'seed_6a91654a0eb479f7'),
  ('ex_idol', 'daily_scene', 1, '오늘 가장 오래 한 일은?', ARRAY['활동','시간','일상']::text[], 'seed_2114a09c00a01e2b'),
  ('ex_idol', 'daily_scene', 1, '지금 옆에 있는 물건은 뭐야?', ARRAY['물건','현재','디테일']::text[], 'seed_2809f0df09e49790'),
  ('ex_idol', 'daily_scene', 1, '오늘 날씨가 기분에 영향 줬어?', ARRAY['날씨','기분','영향']::text[], 'seed_352c586a93bca5f8'),
  ('ex_idol', 'daily_scene', 1, '요즘 자주 가는 카페나 가게가 있어?', ARRAY['카페','가게','일상']::text[], 'seed_63a248af9b389928'),
  ('ex_idol', 'daily_scene', 1, '오늘 스마트폰 스크린타임은 어느 정도?', ARRAY['스크린타임','디지털','일상']::text[], 'seed_239593046be3414a'),
  ('ex_idol', 'daily_scene', 1, '아이돌 때와 다른 지금의 아침 모습은?', ARRAY['아침','비교','일상','변화']::text[], 'seed_477e95662ade6e63'),
  ('ex_idol', 'daily_scene', 1, '오늘 들은 소리 중 가장 좋았던 건?', ARRAY['소리','감각','일상']::text[], 'seed_672d63c5e271f2c8'),
  ('ex_idol', 'daily_scene', 1, '지금 마시고 있는(마실) 음료는?', ARRAY['음료','현재','일상']::text[], 'seed_b119ce04f251d91b'),
  ('ex_idol', 'daily_scene', 1, '오늘 산책했어?', ARRAY['산책','건강','일상']::text[], 'seed_7a736447034a872e'),
  ('ex_idol', 'daily_scene', 1, '요즘 자주 입는 스타일은?', ARRAY['패션','스타일','일상']::text[], 'seed_862c9269f28b5205'),
  ('ex_idol', 'daily_scene', 1, '오늘 가장 맛있게 먹은 건?', ARRAY['음식','맛','오늘']::text[], 'seed_ab63fec549cd4a58'),
  ('ex_idol', 'daily_scene', 1, '지금 방 안 온도는 어때?', ARRAY['온도','환경','현재']::text[], 'seed_b55309f328b08a4f'),
  ('ex_idol', 'daily_scene', 1, '오늘 요리한 거 있어?', ARRAY['요리','일상','활동']::text[], 'seed_e352525d1f7ec44b'),
  ('ex_idol', 'daily_scene', 1, '요즘 잠드는 시간은 보통 몇 시?', ARRAY['수면','시간','일상']::text[], 'seed_7e4fea2cd2219c3a'),
  ('ex_idol', 'daily_scene', 1, '오늘 만난 사람이 있어?', ARRAY['만남','사람','일상']::text[], 'seed_2050cc9951e1222c'),
  ('ex_idol', 'daily_scene', 1, '지금 방에서 보이는 풍경은?', ARRAY['풍경','환경','현재']::text[], 'seed_3936d691e2dba109'),
  ('ex_idol', 'daily_scene', 1, '오늘 택시/버스/지하철 탔어?', ARRAY['교통','이동','일상']::text[], 'seed_f505f78f756afa2e'),
  ('ex_idol', 'daily_scene', 1, '요즘 장바구니에 넣어둔 거 있어?', ARRAY['쇼핑','장바구니','일상']::text[], 'seed_6e6b11857b5688d1'),
  ('ex_idol', 'daily_scene', 1, '오늘 가장 기분 좋았던 순간은?', ARRAY['기분','순간','긍정']::text[], 'seed_faf86009e32eefda'),
  ('ex_idol', 'daily_scene', 1, '아이돌 때 안 했는데 지금 하는 것은?', ARRAY['변화','새로운','비교']::text[], 'seed_05898c6b973e7288'),
  ('ex_idol', 'daily_scene', 1, '오늘 SNS에 뭐 올렸어?', ARRAY['SNS','게시','일상']::text[], 'seed_051a56f14f423471'),
  ('ex_idol', 'daily_scene', 1, '지금 쓰고 있는 향수나 바디로션은?', ARRAY['향수','뷰티','일상']::text[], 'seed_93ed493d141717f4'),
  ('ex_idol', 'daily_scene', 1, '오늘 카페인 몇 잔 마셨어?', ARRAY['카페인','커피','일상']::text[], 'seed_7f3b92086c287477'),
  ('ex_idol', 'daily_scene', 1, '요즘 가장 많이 듣는 팟캐스트/라디오가 있어?', ARRAY['팟캐스트','미디어','취향']::text[], 'seed_e701ed9ee8005501'),
  ('ex_idol', 'daily_scene', 1, '오늘 제일 오래 머문 장소는?', ARRAY['장소','시간','일상']::text[], 'seed_7461a8521745ea1f'),
  ('ex_idol', 'daily_scene', 1, '지금 충전 중인 기기가 있어?', ARRAY['기기','디지털','디테일']::text[], 'seed_21fc34dd2afe4c2a'),
  ('ex_idol', 'daily_scene', 1, '요즘 배달 자주 시켜?', ARRAY['배달','음식','일상']::text[], 'seed_2683129ce4ad3020'),
  ('ex_idol', 'daily_scene', 1, '오늘 하루 중 가장 바빴던 시간은?', ARRAY['바쁨','시간','일상']::text[], 'seed_abd897ba4196c02a'),
  ('ex_idol', 'daily_scene', 1, '아이돌 시절에 비해 지금 여유로운 부분은?', ARRAY['여유','비교','변화']::text[], 'seed_e699d838b88d2920'),
  ('ex_idol', 'daily_scene', 1, '오늘 물 몇 잔 마셨어?', ARRAY['물','건강','일상']::text[], 'seed_00940698f19a7b81'),
  ('ex_idol', 'daily_scene', 1, '지금 켜져 있는 조명은 어떤 색?', ARRAY['조명','환경','디테일']::text[], 'seed_36d00c537d9e3460'),
  ('ex_idol', 'daily_scene', 1, '요즘 자주 보는 유튜브 채널은?', ARRAY['유튜브','채널','취향']::text[], 'seed_5e15d994c24264a9'),
  ('ex_idol', 'daily_scene', 1, '오늘 가장 오래 본 화면은?', ARRAY['화면','시간','디지털']::text[], 'seed_d5a30a20846c2e96'),
  ('ex_idol', 'daily_scene', 1, '아이돌 때 못 했는데 지금 맘껏 하는 건?', ARRAY['자유','변화','비교']::text[], 'seed_d0d1b0a1eea17f6b'),
  ('ex_idol', 'daily_scene', 1, '오늘 가장 많이 걸은 거리는?', ARRAY['걷기','건강','일상']::text[], 'seed_80c6cd7b9d7eb876'),
  ('ex_idol', 'daily_scene', 1, '지금 방 안 가장 눈에 띄는 물건은?', ARRAY['물건','공간','디테일']::text[], 'seed_59417d015b97e52c'),
  ('ex_idol', 'daily_scene', 2, '아이돌 활동 때와 비교해서 지금의 하루 루틴은 어떻게 달라?', ARRAY['루틴','비교','변화','일상']::text[], 'seed_6189db0f23243372'),
  ('ex_idol', 'daily_scene', 2, '요즘 자기 관리에 가장 신경 쓰는 부분은?', ARRAY['자기관리','건강','뷰티','일상']::text[], 'seed_d227d7dc8101335c'),
  ('ex_idol', 'daily_scene', 2, '아이돌 때 먹지 못했던 음식 중 지금 맘껏 먹는 건?', ARRAY['음식','자유','비교','일상']::text[], 'seed_73a0d41ce5af13ae'),
  ('ex_idol', 'daily_scene', 2, '요즘 하루 중 가장 소중한 시간은 언제야?', ARRAY['소중','시간','일상','가치']::text[], 'seed_ebe12ce565896225'),
  ('ex_idol', 'daily_scene', 2, '연습실에서의 하루와 지금의 하루를 비교해준다면?', ARRAY['연습실','비교','일상','변화']::text[], 'seed_fc6ba017ba47ac5e'),
  ('ex_idol', 'daily_scene', 2, '요즘 새롭게 시도하고 있는 것이 있어?', ARRAY['도전','새로움','현재','성장']::text[], 'seed_650f768981c99be1'),
  ('ex_idol', 'daily_scene', 2, '아이돌 시절에는 당연했는데 지금은 특별하게 느껴지는 건?', ARRAY['특별','변화','감상','비교']::text[], 'seed_ff117085c239b384'),
  ('ex_idol', 'daily_scene', 2, '요즘 SNS를 어떻게 활용하고 있어?', ARRAY['SNS','활용','현재','소통']::text[], 'seed_017c78e30703616c'),
  ('ex_idol', 'daily_scene', 2, '일상에서 아이돌 시절 트레이닝이 도움되는 순간은?', ARRAY['트레이닝','도움','일상','경험']::text[], 'seed_f8e3b0adc8a365df'),
  ('ex_idol', 'daily_scene', 2, '요즘 가장 즐거운 일과 가장 귀찮은 일은?', ARRAY['즐거움','귀찮음','일상','비교']::text[], 'seed_b5160660b365362c'),
  ('ex_idol', 'daily_scene', 2, '아이돌 때 배운 시간 관리법을 지금도 쓰고 있어?', ARRAY['시간관리','스킬','활용','일상']::text[], 'seed_ef61050c512e73ef'),
  ('ex_idol', 'daily_scene', 2, '요즘 자주 만나는 사람들과 주로 뭐 하면서 보내?', ARRAY['친구','활동','일상','관계']::text[], 'seed_9ae864842e4e7c43'),
  ('ex_idol', 'daily_scene', 2, '아이돌 활동 후 ''평범한 일상''의 매력을 느끼는 순간은?', ARRAY['일상','매력','변화','감상']::text[], 'seed_f703b953d071c5cf'),
  ('ex_idol', 'daily_scene', 2, '요즘 자기 스타일(패션/메이크업)에 어떤 변화가 있어?', ARRAY['스타일','변화','패션','현재']::text[], 'seed_6514142666bdd4a1'),
  ('ex_idol', 'daily_scene', 2, '일상에서 ''이건 아이돌 때 경험 덕분이야''라고 느끼는 순간은?', ARRAY['경험','덕분','일상','성장']::text[], 'seed_7fd0895ef38ef1a4'),
  ('ex_idol', 'daily_scene', 2, '요즘 뭘 배우고 있거나 배우고 싶은 게 있어?', ARRAY['배움','관심사','성장','현재']::text[], 'seed_850f81cd1e75a07c'),
  ('ex_idol', 'daily_scene', 2, '아이돌 때와 지금, 먹는 양이나 스타일이 달라졌어?', ARRAY['식사','변화','건강','비교']::text[], 'seed_f5fb68743b85cadd'),
  ('ex_idol', 'daily_scene', 2, '주말에 주로 어떻게 보내?', ARRAY['주말','여가','일상','쉼']::text[], 'seed_9be0186d1df478e0'),
  ('ex_idol', 'daily_scene', 2, '요즘 자기 방/집에서 가장 좋아하는 코너는?', ARRAY['공간','집','취향','쉼']::text[], 'seed_16d79cdb03a48ea7'),
  ('ex_idol', 'daily_scene', 2, '아이돌 활동 후 새로 생긴 취미가 있다면?', ARRAY['취미','새로운','변화','현재']::text[], 'seed_def82a1cf62dcaac'),
  ('ex_idol', 'daily_scene', 2, '요즘 건강관리를 위해 특별히 하는 것은?', ARRAY['건강','관리','일상','습관']::text[], 'seed_8e0effac59df6d8f'),
  ('ex_idol', 'daily_scene', 2, '아이돌 시절의 일상과 지금의 일상, 어느 쪽이 더 좋아?', ARRAY['비교','선호','일상','솔직']::text[], 'seed_3bacf53a4b76342c'),
  ('ex_idol', 'daily_scene', 2, '요즘 일상에서 가장 ''아이돌답다''고 느끼는 순간은?', ARRAY['아이돌답다','순간','일상','정체성']::text[], 'seed_51aafe329aee29ae'),
  ('ex_idol', 'daily_scene', 2, '밤에 잠들기 전 주로 뭘 해?', ARRAY['취침전','루틴','일상','습관']::text[], 'seed_1ef53f2756b3101f'),
  ('ex_idol', 'daily_scene', 2, '요즘 가장 신경 쓰이는 생활 습관은?', ARRAY['습관','생활','관심','일상']::text[], 'seed_660892cbefc8956c'),
  ('ex_idol', 'daily_scene', 3, '아이돌 후의 일상에서 가장 큰 ''자유''는 뭐라고 생각해?', ARRAY['자유','일상','변화','가치']::text[], 'seed_5bc80deae7393df1'),
  ('ex_idol', 'daily_scene', 3, '지금의 일상을 통해 자기 자신에 대해 새롭게 알게 된 건?', ARRAY['자기발견','일상','성장','인사이트']::text[], 'seed_986630a1cc441733'),
  ('ex_idol', 'daily_scene', 3, '아이돌 때의 스케줄과 지금의 자유로운 시간, 각각의 장단점은?', ARRAY['스케줄','자유','비교','장단점']::text[], 'seed_33517c88f4f8bf60'),
  ('ex_idol', 'daily_scene', 3, '일상에서 ''나만의 무대''라고 느끼는 순간이 있어?', ARRAY['무대','일상','전환','의미']::text[], 'seed_3f974bffd89e9cda'),
  ('ex_idol', 'daily_scene', 3, '일상의 반복 속에서 의미를 찾는 자기만의 방법은?', ARRAY['반복','의미','방법','일상']::text[], 'seed_08c3886fc3fac622'),
  ('ex_idol', 'daily_scene', 3, '아이돌 이후의 삶에서 가장 도전적이었던 적응 과정은?', ARRAY['적응','도전','변화','성장']::text[], 'seed_f7d6e57c617ced7c'),
  ('ex_idol', 'daily_scene', 3, '지금의 하루가 미래의 자기에게 어떤 의미가 될 것 같아?', ARRAY['미래','의미','일상','가치']::text[], 'seed_9d69934e098223b1'),
  ('ex_idol', 'daily_scene', 3, '일상에서 가장 평화로운 순간을 상세하게 묘사해준다면?', ARRAY['평화','순간','묘사','감성']::text[], 'seed_e35cb17fe5949cfb'),
  ('ex_idol', 'daily_scene', 3, '아이돌 때와 지금, ''시간''의 흐름을 느끼는 방식이 달라졌어?', ARRAY['시간','감각','변화','철학']::text[], 'seed_73da7aecbedd89da'),
  ('ex_idol', 'daily_scene', 3, '지금의 일상을 하나의 단어로 정의한다면?', ARRAY['정의','단어','일상','자기표현']::text[], 'seed_6896e54370f42c4f'),
  ('ex_idol', 'daily_scene', 3, '일상 속에서 ''아, 이 시간이 소중하다''고 느끼는 구체적 순간은?', ARRAY['소중','순간','일상','감사']::text[], 'seed_92d760b11bd1fde7'),
  ('ex_idol', 'daily_scene', 3, '아이돌에서 일상으로의 전환이 자기 삶의 질에 어떤 영향을 줬어?', ARRAY['전환','삶의질','영향','변화']::text[], 'seed_b851434e96df282d'),
  ('ex_idol', 'daily_scene', 3, '지금의 일상 중 10년 후에도 계속하고 싶은 건?', ARRAY['10년후','지속','일상','가치']::text[], 'seed_effea6be4ba20c5a'),
  ('ex_idol', 'daily_scene', 3, '혼자 보내는 시간의 의미가 아이돌 때와 어떻게 달라졌어?', ARRAY['혼자','시간','의미','변화']::text[], 'seed_11adbe535f5baf3f'),
  ('ex_idol', 'daily_scene', 3, '지금의 하루를 다큐멘터리로 찍는다면 가장 인상적인 장면은?', ARRAY['다큐','장면','일상','표현']::text[], 'seed_873a5a6d4acc730d'),
  ('ex_idol', 'behind_story', 1, '오디션을 본 적 있어?', ARRAY['오디션','시작','경험']::text[], 'seed_d963abb6f3a0b3a3'),
  ('ex_idol', 'behind_story', 1, '연습생 기간은 얼마나 됐어?', ARRAY['연습생','기간','과거']::text[], 'seed_12be164397ddc851'),
  ('ex_idol', 'behind_story', 1, '첫 무대에서의 감정을 한마디로?', ARRAY['첫무대','감정','기억']::text[], 'seed_18274bd3d78b3fe0'),
  ('ex_idol', 'behind_story', 1, '활동 시절 가장 좋아했던 간식은?', ARRAY['간식','활동시절','일상']::text[], 'seed_5b0144d0c13d8463'),
  ('ex_idol', 'behind_story', 1, '연습실에서 가장 많이 했던 행동은?', ARRAY['연습실','행동','과거']::text[], 'seed_0e597a2a7ad1334c'),
  ('ex_idol', 'behind_story', 1, '활동 시절 잠이 부족할 때 어떻게 버텼어?', ARRAY['수면부족','버팀','방법']::text[], 'seed_60fee98b58988460'),
  ('ex_idol', 'behind_story', 1, '첫 번째 팬레터는 어떤 내용이었어?', ARRAY['팬레터','처음','감동']::text[], 'seed_f871bd77eece5792'),
  ('ex_idol', 'behind_story', 1, '활동 당시 컴백 준비 중 가장 긴장된 순간은?', ARRAY['컴백','긴장','준비']::text[], 'seed_ad8e26630a2f72e0'),
  ('ex_idol', 'behind_story', 1, '연습 중 가장 많이 들은 피드백은?', ARRAY['피드백','연습','성장']::text[], 'seed_0c7c7ed4255e8acb'),
  ('ex_idol', 'behind_story', 1, '활동 시절 가장 좋아했던 의상 스타일은?', ARRAY['의상','스타일','취향']::text[], 'seed_23c37f77ad282afc'),
  ('ex_idol', 'behind_story', 1, '숙소 생활에서 가장 기억나는 건?', ARRAY['숙소','기억','일상']::text[], 'seed_97571743777454fa'),
  ('ex_idol', 'behind_story', 1, '활동 중 가장 많이 먹었던 편의점 음식은?', ARRAY['편의점','음식','과거']::text[], 'seed_f5f4b89deb972a4b'),
  ('ex_idol', 'behind_story', 1, '첫 무대 전날 밤의 기분은?', ARRAY['전날밤','첫무대','감정']::text[], 'seed_43cd94a20a9a8370'),
  ('ex_idol', 'behind_story', 1, '활동 시절 자주 가던 장소(유형)는?', ARRAY['장소','활동시절','일상']::text[], 'seed_6bc7ff632f0fcc44'),
  ('ex_idol', 'behind_story', 1, '연습생 때 가장 힘들었던 과목(보컬/댄스/랩 등)은?', ARRAY['과목','힘듦','연습생']::text[], 'seed_4cddcfdbdc513726'),
  ('ex_idol', 'behind_story', 1, '활동 시절 해어스타일 중 가장 마음에 들었던 건?', ARRAY['헤어','스타일','과거']::text[], 'seed_4377c4c832d3cc4f'),
  ('ex_idol', 'behind_story', 1, '첫 녹음실 경험은 어땠어?', ARRAY['녹음실','처음','경험']::text[], 'seed_9df0257c1c37fa78'),
  ('ex_idol', 'behind_story', 1, '활동 시절 가장 재밌었던 촬영은?', ARRAY['촬영','재미','에피소드']::text[], 'seed_06cdefed9c4f8572'),
  ('ex_idol', 'behind_story', 1, '연습 중 가장 성취감 느꼈던 순간은?', ARRAY['성취','연습','순간']::text[], 'seed_b8db4364401a1eac'),
  ('ex_idol', 'behind_story', 1, '활동 시절 팬을 처음 만났을 때 기분은?', ARRAY['팬','처음만남','감정']::text[], 'seed_10102287b2ebb05b'),
  ('ex_idol', 'behind_story', 1, '가장 오래 연습한 안무의 특징은?', ARRAY['안무','연습','특징']::text[], 'seed_a1e3ffdd3f2cebcc'),
  ('ex_idol', 'behind_story', 1, '활동 중 가장 추웠던/더웠던 무대는?', ARRAY['날씨','무대','에피소드']::text[], 'seed_2f8173cf12b7c1bd'),
  ('ex_idol', 'behind_story', 1, '연습생 동기 중 제일 재밌었던 사람의 특징은?', ARRAY['동기','재미','성격']::text[], 'seed_0d6de2ddb21f9827'),
  ('ex_idol', 'behind_story', 1, '활동 시절 가장 많이 불렀던 노래는?', ARRAY['노래','많이불름','과거']::text[], 'seed_a87eff3ddf2df155'),
  ('ex_idol', 'behind_story', 1, '이동 중 버스/밴에서 주로 뭘 했어?', ARRAY['이동','버스','일상']::text[], 'seed_40a85230719b4173'),
  ('ex_idol', 'behind_story', 1, '데뷔 소식을 들었을 때 제일 먼저 한 건?', ARRAY['데뷔','소식','반응']::text[], 'seed_9773dd3e4d5a33fd'),
  ('ex_idol', 'behind_story', 1, '활동 중 뮤비 촬영 시 가장 인상적이었던 세트는?', ARRAY['뮤비','세트','인상적']::text[], 'seed_0fb3f875e977b83a'),
  ('ex_idol', 'behind_story', 1, '연습생 때 자유시간에 주로 뭘 했어?', ARRAY['자유시간','연습생','여가']::text[], 'seed_0f62d45ab3d9cfeb'),
  ('ex_idol', 'behind_story', 1, '활동 시절 가장 감동받은 팬 이벤트는?', ARRAY['팬이벤트','감동','기억']::text[], 'seed_0fa5f170edfa6e42'),
  ('ex_idol', 'behind_story', 1, '무대에서 실수한 적 있어? (가볍게)', ARRAY['실수','무대','에피소드']::text[], 'seed_38d9b32e8a53dc80'),
  ('ex_idol', 'behind_story', 1, '활동 시절 제일 좋아했던 방송/무대는?', ARRAY['방송','무대','기억']::text[], 'seed_5e78b8bba030e29b'),
  ('ex_idol', 'behind_story', 1, '연습생 때 가장 존경했던 선배의 특징은?', ARRAY['선배','존경','특징']::text[], 'seed_709508256bd79dac'),
  ('ex_idol', 'behind_story', 1, '활동 중 새벽까지 연습한 적 있어?', ARRAY['새벽','연습','노력']::text[], 'seed_c51a16e2e5c96dfc'),
  ('ex_idol', 'behind_story', 1, '첫 방송 출연 때 기억나는 건?', ARRAY['첫방송','기억','긴장']::text[], 'seed_35eece21279e5388'),
  ('ex_idol', 'behind_story', 1, '활동 시절 ''이건 비밀''이라고 했던 소소한 것은?', ARRAY['비밀','소소','재미']::text[], 'seed_e87e7c0973abc8b8'),
  ('ex_idol', 'behind_story', 1, '연습 중 좌절했다가 다시 일어난 경험이 있어?', ARRAY['좌절','극복','연습']::text[], 'seed_1e784287ce3774c3'),
  ('ex_idol', 'behind_story', 1, '활동 시절 가장 자주 쓴 화장품은?', ARRAY['화장품','뷰티','과거']::text[], 'seed_de518c897a2baf82'),
  ('ex_idol', 'behind_story', 1, '무대 준비하면서 가장 시간 많이 걸린 건?', ARRAY['준비','시간','무대']::text[], 'seed_ee66e9018c811a63'),
  ('ex_idol', 'behind_story', 1, '활동 시절 다른 팀과 친하게 지냈던 에피소드가 있어?', ARRAY['다른팀','친분','에피소드']::text[], 'seed_350e482e02ea0a07'),
  ('ex_idol', 'behind_story', 1, '가장 마지막 활동(무대/방송)의 기분은?', ARRAY['마지막','활동','감정']::text[], 'seed_b566713649faffd2'),
  ('ex_idol', 'behind_story', 2, '연습생 시절 가장 큰 성장을 이끈 순간은?', ARRAY['성장','순간','연습생','변화']::text[], 'seed_02fdeefd881c37d3'),
  ('ex_idol', 'behind_story', 2, '데뷔 전과 후의 자기 인식 차이는?', ARRAY['데뷔','자기인식','변화','비교']::text[], 'seed_e840a9c48c207c14'),
  ('ex_idol', 'behind_story', 2, '활동 시절 팬과의 관계에서 가장 기억에 남는 에피소드는?', ARRAY['팬','관계','에피소드','감동']::text[], 'seed_f0b127c966e0dc0a'),
  ('ex_idol', 'behind_story', 2, '아이돌 활동 중 가장 성장했다고 느낀 스킬은?', ARRAY['스킬','성장','아이돌','자기평가']::text[], 'seed_2c06a0e6d0b93725'),
  ('ex_idol', 'behind_story', 2, '활동을 마치기로 한 결정의 배경은? (공유 가능한 범위에서)', ARRAY['은퇴','결정','배경','솔직']::text[], 'seed_ead93888f69d6fc4'),
  ('ex_idol', 'behind_story', 2, '아이돌 산업에서 배운 가장 값진 교훈은?', ARRAY['교훈','산업','배움','경험']::text[], 'seed_6250c0351115fbbe'),
  ('ex_idol', 'behind_story', 2, '멤버(동료)들과의 관계에서 가장 좋았던 기억은?', ARRAY['멤버','관계','기억','우정']::text[], 'seed_42830972ed4cf245'),
  ('ex_idol', 'behind_story', 2, '무대 위에서 가장 ''살아있다''고 느낀 순간은?', ARRAY['살아있음','무대','순간','감정']::text[], 'seed_a12cc7b72eb1051f'),
  ('ex_idol', 'behind_story', 2, '팬들에게 전하지 못한 이야기가 있다면?', ARRAY['팬','이야기','솔직','메시지']::text[], 'seed_2712e5238afb4ddf'),
  ('ex_idol', 'behind_story', 2, '활동 중 가장 도전적이었던 프로젝트는?', ARRAY['도전','프로젝트','활동','경험']::text[], 'seed_1c421fbffe69c657'),
  ('ex_idol', 'behind_story', 2, '아이돌 생활에서 가장 의외였던 점은?', ARRAY['의외','발견','아이돌','인사이트']::text[], 'seed_38ba5897d040723a'),
  ('ex_idol', 'behind_story', 2, '활동 시절 가장 큰 위기와 그 극복 방법은?', ARRAY['위기','극복','활동','성장']::text[], 'seed_4473ff5d6f6ad035'),
  ('ex_idol', 'behind_story', 2, '무대 뒤에서의 일상을 팬들이 안다면 놀랄 부분은?', ARRAY['무대뒤','일상','비하인드','발견']::text[], 'seed_65326a6d1cb7249f'),
  ('ex_idol', 'behind_story', 2, '아이돌 활동이 자기 예술적 감각에 준 영향은?', ARRAY['예술','감각','영향','성장']::text[], 'seed_94815d169d8aff27'),
  ('ex_idol', 'behind_story', 2, '활동 중 팬과 가장 가까웠다고 느낀 순간은?', ARRAY['팬','가까움','순간','소통']::text[], 'seed_01a25e4177cffb9a'),
  ('ex_idol', 'behind_story', 2, '연습생 때 가장 많이 들었던 음악의 영향은?', ARRAY['음악','영향','연습생','취향']::text[], 'seed_90de794077010a30'),
  ('ex_idol', 'behind_story', 2, '활동 시절의 ''최고의 날''을 꼽는다면?', ARRAY['최고','날','활동','기억']::text[], 'seed_2f68b4b491c1c6ad'),
  ('ex_idol', 'behind_story', 2, '아이돌로서 가장 힘들었던 건 체력? 멘탈? 인간관계?', ARRAY['힘듦','영역','아이돌','솔직']::text[], 'seed_163ca7754c496552'),
  ('ex_idol', 'behind_story', 2, '멤버(동료)에게 지금 전하고 싶은 한마디는?', ARRAY['멤버','메시지','감사','우정']::text[], 'seed_55796a67809338e7'),
  ('ex_idol', 'behind_story', 2, '활동 중 자기만의 무대 루틴이 있었어?', ARRAY['루틴','무대','습관','아이돌']::text[], 'seed_3f4c98dcd55e0889'),
  ('ex_idol', 'behind_story', 2, '팬미팅에서 가장 준비를 많이 한 건?', ARRAY['팬미팅','준비','노력','에피소드']::text[], 'seed_5094516510caac3e'),
  ('ex_idol', 'behind_story', 2, '활동 시절 가장 큰 영감을 준 선배/아티스트의 특징은?', ARRAY['영감','선배','아티스트','롤모델']::text[], 'seed_ad55c3d45c153602'),
  ('ex_idol', 'behind_story', 2, '아이돌 활동에서 자기가 가장 성숙해진 계기는?', ARRAY['성숙','계기','성장','아이돌']::text[], 'seed_371d4a640429b821'),
  ('ex_idol', 'behind_story', 2, '무대 실수를 커버한 경험이 있어? 어떻게 했어?', ARRAY['실수','커버','무대','대처']::text[], 'seed_f4a315b51aa37e97'),
  ('ex_idol', 'behind_story', 2, '활동을 마친 직후의 감정은 어땠어?', ARRAY['은퇴직후','감정','솔직','변화']::text[], 'seed_e6a77c047ebda1af'),
  ('ex_idol', 'behind_story', 3, '아이돌 활동 전체를 한 편의 이야기로 요약한다면 어떤 스토리야?', ARRAY['스토리','요약','활동전체','서사']::text[], 'seed_e7bb48e88bb35be5'),
  ('ex_idol', 'behind_story', 3, '그 시절 가장 빛났던 순간과 가장 어두웠던 순간을 모두 이야기해줄 수 있어?', ARRAY['빛','어둠','대비','솔직']::text[], 'seed_607958456c465918'),
  ('ex_idol', 'behind_story', 3, '아이돌이라는 경험을 통해 ''사람''에 대해 배운 가장 깊은 것은?', ARRAY['사람','배움','깊이','인사이트']::text[], 'seed_57200dc74048e6dc'),
  ('ex_idol', 'behind_story', 3, '무대와 팬 사이의 거리감에 대해 솔직하게 이야기한다면?', ARRAY['거리감','팬','무대','솔직']::text[], 'seed_61a7cd8cf4c1127f'),
  ('ex_idol', 'behind_story', 3, '아이돌 활동이 자기의 ''사랑''에 대한 생각을 어떻게 바꿨어?', ARRAY['사랑','변화','가치관','성장']::text[], 'seed_ccbe30f48bfe6cf4'),
  ('ex_idol', 'behind_story', 3, '아이돌 산업의 빛과 그림자를 균형 있게 이야기해준다면?', ARRAY['빛','그림자','산업','균형']::text[], 'seed_798d73e1fd36243a'),
  ('ex_idol', 'behind_story', 3, '지금의 자기가 데뷔 당시의 자기에게 쓰는 장문 편지의 핵심은?', ARRAY['편지','과거','메시지','성장']::text[], 'seed_a9d7bbbe6781cd0c'),
  ('ex_idol', 'behind_story', 3, '''꿈을 이룬다는 것''과 ''꿈이 끝난 후''에 대해 솔직하게 이야기해줄 수 있어?', ARRAY['꿈','끝','이후','철학']::text[], 'seed_abe2ac420b890f39'),
  ('ex_idol', 'behind_story', 3, '아이돌 경험이 자기의 삶 전체에서 어떤 무게를 차지해?', ARRAY['무게','인생','비중','가치']::text[], 'seed_bd5d80eb09abd183'),
  ('ex_idol', 'behind_story', 3, '활동을 마친 후 가장 긴 밤을 보낸 적이 있다면 그때 어떤 생각을 했어?', ARRAY['긴밤','생각','감정','은퇴후']::text[], 'seed_82df6038fce630d7'),
  ('ex_idol', 'behind_story', 3, '아이돌로서의 자기와 지금의 자기를 모두 포함하는 하나의 정체성은?', ARRAY['정체성','통합','과거','현재']::text[], 'seed_ffcdb61feabff4a2'),
  ('ex_idol', 'behind_story', 3, '미래에 자기 이야기를 누군가에게 들려준다면 어떤 메시지를 담고 싶어?', ARRAY['메시지','미래','이야기','가치']::text[], 'seed_6394056ff04e6456'),
  ('ex_idol', 'behind_story', 3, '아이돌 문화에 대해 세상에 오해 없이 전하고 싶은 한 가지는?', ARRAY['오해','진실','문화','전달']::text[], 'seed_d4fb2bd2a1600f1f'),
  ('ex_idol', 'behind_story', 3, '만약 자서전을 쓴다면 제목과 첫 문장은?', ARRAY['자서전','제목','첫문장','창의']::text[], 'seed_ff4c5932f629028d'),
  ('ex_idol', 'behind_story', 3, '아이돌 경험이 ''나''라는 사람을 어떻게 조각했는지 말해준다면?', ARRAY['조각','정체성','경험','성장']::text[], 'seed_b318d9688d15b562'),
  ('ex_idol', 'roleplay_flavor', 1, '지금 솔로 앨범을 낸다면 타이틀곡 제목은?', ARRAY['앨범','타이틀','상상','음악']::text[], 'seed_91ca2c8171754b45'),
  ('ex_idol', 'roleplay_flavor', 1, '무대에 한 가지 마법을 쓸 수 있다면?', ARRAY['마법','무대','상상','재미']::text[], 'seed_acc2c63d709d84fd'),
  ('ex_idol', 'roleplay_flavor', 1, '자기만의 응원봉 디자인은?', ARRAY['응원봉','디자인','팬','상상']::text[], 'seed_3c884d5a98e24ed0'),
  ('ex_idol', 'roleplay_flavor', 1, '아이돌 게임 캐릭터가 된다면 스킬명은?', ARRAY['게임','캐릭터','스킬','상상']::text[], 'seed_9eaedb959b83b00c'),
  ('ex_idol', 'roleplay_flavor', 1, '오늘의 센터 포즈를 하나 만든다면?', ARRAY['센터','포즈','무대','재미']::text[], 'seed_ba0811fa53839019'),
  ('ex_idol', 'roleplay_flavor', 1, '콘서트 앵콜곡으로 부를 노래 한 곡은?', ARRAY['콘서트','앵콜','노래','선택']::text[], 'seed_03a3de3a58749ae5'),
  ('ex_idol', 'roleplay_flavor', 1, '팬미팅에서 할 미니게임을 하나 만든다면?', ARRAY['팬미팅','게임','아이디어','재미']::text[], 'seed_baa827d1a87e10b9'),
  ('ex_idol', 'roleplay_flavor', 1, '무대 위에서의 자기 별명을 새로 만든다면?', ARRAY['별명','무대','콘셉트','재미']::text[], 'seed_43b5d17318fb76c4'),
  ('ex_idol', 'roleplay_flavor', 1, '솔로 뮤비의 배경 장소를 고른다면?', ARRAY['뮤비','장소','상상','연출']::text[], 'seed_00ff44de2beb3b00'),
  ('ex_idol', 'roleplay_flavor', 1, '무대 의상을 직접 디자인한다면 포인트는?', ARRAY['의상','디자인','무대','패션']::text[], 'seed_268859bb3df6ec31'),
  ('ex_idol', 'roleplay_flavor', 1, '팬에게 보내는 마법의 한마디는?', ARRAY['팬','마법','메시지','콘셉트']::text[], 'seed_07dbedad56822415'),
  ('ex_idol', 'roleplay_flavor', 1, '자기 테마곡의 분위기를 정한다면?', ARRAY['테마곡','분위기','음악','상상']::text[], 'seed_f478d84af7f22870'),
  ('ex_idol', 'roleplay_flavor', 1, '무대에 등장할 때 연출 효과를 고른다면?', ARRAY['연출','등장','무대','상상']::text[], 'seed_f5c1583ea046b9c5'),
  ('ex_idol', 'roleplay_flavor', 1, '라이벌 아이돌(가상)과의 배틀곡 제목은?', ARRAY['라이벌','배틀','가상','음악']::text[], 'seed_c205ad5f92f35f4e'),
  ('ex_idol', 'roleplay_flavor', 1, '팬에게 줄 ''럭키 포토카드'' 콘셉트는?', ARRAY['포토카드','콘셉트','팬','디자인']::text[], 'seed_3c66e664431edd75'),
  ('ex_idol', 'roleplay_flavor', 1, '오늘의 아이돌 모드 전투력은?', ARRAY['전투력','모드','재미','상태']::text[], 'seed_3112cec566ddb35a'),
  ('ex_idol', 'roleplay_flavor', 1, '이세계에서 아이돌을 한다면 어떤 장르의 음악?', ARRAY['이세계','장르','상상','음악']::text[], 'seed_68ad50f86cd090d9'),
  ('ex_idol', 'roleplay_flavor', 1, '콘서트 굿즈를 하나 만든다면?', ARRAY['굿즈','디자인','콘서트','팬']::text[], 'seed_4aac4063a42a016e'),
  ('ex_idol', 'roleplay_flavor', 1, '무대에서 쓸 소품을 하나 고른다면?', ARRAY['소품','무대','연출','선택']::text[], 'seed_bb9055e16f64b965'),
  ('ex_idol', 'roleplay_flavor', 1, '자기만의 팬 호칭을 만든다면?', ARRAY['팬','호칭','콘셉트','네이밍']::text[], 'seed_3ddb8c54058d45e8'),
  ('ex_idol', 'roleplay_flavor', 1, '아이돌 RPG에서 자기 직업군은?', ARRAY['RPG','직업','게임','상상']::text[], 'seed_1b7880cadd6f4721'),
  ('ex_idol', 'roleplay_flavor', 1, '무대 위 시그니처 제스처를 만든다면?', ARRAY['시그니처','제스처','무대','콘셉트']::text[], 'seed_bb0a2afcc3e24c90'),
  ('ex_idol', 'roleplay_flavor', 1, '가상 유닛을 만든다면 유닛명과 콘셉트는?', ARRAY['유닛','콘셉트','가상','팀']::text[], 'seed_2305269b4aa4f7a0'),
  ('ex_idol', 'roleplay_flavor', 1, '무대 배경 VCR을 만든다면 어떤 영상?', ARRAY['VCR','영상','무대','연출']::text[], 'seed_f821b7116c5693a1'),
  ('ex_idol', 'roleplay_flavor', 1, '팬 사인회에서 특별히 해주고 싶은 건?', ARRAY['사인회','특별','팬','서비스']::text[], 'seed_63032068bc8b97b7'),
  ('ex_idol', 'roleplay_flavor', 1, '오늘의 아이돌 미션을 하나 정한다면?', ARRAY['미션','아이돌','도전','재미']::text[], 'seed_81dde46c42e83a2b'),
  ('ex_idol', 'roleplay_flavor', 1, '콘서트 인트로 멘트를 만들어본다면?', ARRAY['인트로','멘트','콘서트','콘셉트']::text[], 'seed_80a6ddbf10a642cd'),
  ('ex_idol', 'roleplay_flavor', 1, '자기를 표현하는 이모지 조합 3개는?', ARRAY['이모지','자기표현','재미','상징']::text[], 'seed_7dd96504bc156cd3'),
  ('ex_idol', 'roleplay_flavor', 1, '가상 콜라보를 한다면 어떤 장르의 아티스트와?', ARRAY['콜라보','장르','가상','음악']::text[], 'seed_3fa60193dcb730ab'),
  ('ex_idol', 'roleplay_flavor', 1, '무대 조명 색을 하나 고른다면?', ARRAY['조명','색','무대','연출']::text[], 'seed_6c076827b84fa4c6'),
  ('ex_idol', 'roleplay_flavor', 1, '팬에게 보내는 보이스 메시지 한마디는?', ARRAY['보이스','메시지','팬','콘셉트']::text[], 'seed_7aa00a7af17ca800'),
  ('ex_idol', 'roleplay_flavor', 1, '아이돌 카페를 연다면 시그니처 메뉴는?', ARRAY['카페','메뉴','아이돌','상상']::text[], 'seed_11d9655a782d3b95'),
  ('ex_idol', 'roleplay_flavor', 1, '무대 위 승리 포즈를 만든다면?', ARRAY['승리','포즈','무대','재미']::text[], 'seed_af0e96e4d816d155'),
  ('ex_idol', 'roleplay_flavor', 1, '자기를 꽃에 비유한 솔로곡 제목은?', ARRAY['꽃','솔로곡','비유','음악']::text[], 'seed_1555b9460bf51d24'),
  ('ex_idol', 'roleplay_flavor', 1, '팬 투어를 기획한다면 어디로?', ARRAY['투어','장소','팬','기획']::text[], 'seed_4f551ce4c547a311'),
  ('ex_idol', 'roleplay_flavor', 1, '아이돌 세계관에서 자기의 초능력은?', ARRAY['초능력','세계관','상상','캐릭터']::text[], 'seed_0a11eb5e5a46855c'),
  ('ex_idol', 'roleplay_flavor', 1, '오늘의 팬 서비스 아이디어 하나!', ARRAY['팬서비스','아이디어','재미','소통']::text[], 'seed_3c5dc97765d7e7ab'),
  ('ex_idol', 'roleplay_flavor', 1, '무대 의상에 자기만의 시그니처 액세서리를 추가한다면?', ARRAY['액세서리','시그니처','의상','패션']::text[], 'seed_c7a391beeaf68c81'),
  ('ex_idol', 'roleplay_flavor', 1, '팬과 함께하는 챌린지를 만든다면?', ARRAY['챌린지','팬','참여','아이디어']::text[], 'seed_83ad9bfcc49fc08c'),
  ('ex_idol', 'roleplay_flavor', 1, '자기 이름으로 된 별이 있다면 어떤 별?', ARRAY['별','이름','상상','로맨틱']::text[], 'seed_4c634cd4b7e4ffee'),
  ('ex_idol', 'roleplay_flavor', 2, '솔로 앨범의 트랙리스트를 5곡 정도 만들어본다면?', ARRAY['트랙리스트','앨범','음악','창의']::text[], 'seed_4b7864ff7445d3f2'),
  ('ex_idol', 'roleplay_flavor', 2, '가상의 콘서트를 기획한다면 세트리스트 하이라이트는?', ARRAY['콘서트','세트리스트','기획','무대']::text[], 'seed_486b2cbb73c32fb2'),
  ('ex_idol', 'roleplay_flavor', 2, '자기만의 아이돌 세계관 스토리를 만든다면?', ARRAY['세계관','스토리','창작','아이돌']::text[], 'seed_160574519b38cb8f'),
  ('ex_idol', 'roleplay_flavor', 2, '아이돌 생존 프로그램에 다시 나간다면 자기 PR 무대는?', ARRAY['서바이벌','PR','무대','상상']::text[], 'seed_b350debe5274c20b'),
  ('ex_idol', 'roleplay_flavor', 2, '팬과 함께하는 리얼리티 프로그램을 기획한다면?', ARRAY['리얼리티','기획','팬','프로그램']::text[], 'seed_3666ba1ecbd9a121'),
  ('ex_idol', 'roleplay_flavor', 2, '뮤비 감독이 된다면 어떤 스토리의 뮤비를 만들고 싶어?', ARRAY['뮤비','감독','스토리','연출']::text[], 'seed_1e5a3bd26c9a23eb'),
  ('ex_idol', 'roleplay_flavor', 2, '아이돌 멘토링 프로그램을 만든다면 커리큘럼은?', ARRAY['멘토링','커리큘럼','아이돌','기획']::text[], 'seed_5088cf35c2ff0baa'),
  ('ex_idol', 'roleplay_flavor', 2, '콘서트 VIP석 특전을 기획한다면?', ARRAY['VIP','특전','콘서트','기획']::text[], 'seed_900afc9615c4f54d'),
  ('ex_idol', 'roleplay_flavor', 2, '자기를 주인공으로 한 웹드라마 1화 줄거리는?', ARRAY['웹드라마','줄거리','창작','스토리']::text[], 'seed_d20760be538cd869'),
  ('ex_idol', 'roleplay_flavor', 2, '아이돌 테마 보드게임의 핵심 룰을 만든다면?', ARRAY['보드게임','룰','아이돌','창의']::text[], 'seed_acf78f87001826c5'),
  ('ex_idol', 'roleplay_flavor', 2, '가상의 월드투어 첫 도시와 마지막 도시는?', ARRAY['월드투어','도시','기획','상상']::text[], 'seed_a935667daa3dc621'),
  ('ex_idol', 'roleplay_flavor', 2, '팬을 위한 ASMR 콘텐츠를 만든다면 주제는?', ARRAY['ASMR','콘텐츠','팬','아이디어']::text[], 'seed_3504dc51787a30f1'),
  ('ex_idol', 'roleplay_flavor', 2, '아이돌 카드게임에서 자기 카드의 능력치와 특수 스킬은?', ARRAY['카드게임','능력치','스킬','상상']::text[], 'seed_9073d971c4025521'),
  ('ex_idol', 'roleplay_flavor', 2, '무대 의상 라인을 디자인한다면 시즌 테마는?', ARRAY['의상','디자인','시즌','패션']::text[], 'seed_ecd5d2b3171d9fe9'),
  ('ex_idol', 'roleplay_flavor', 2, '자기만의 음악 레이블을 만든다면 이름과 콘셉트는?', ARRAY['레이블','이름','콘셉트','비전']::text[], 'seed_dd20eeca2390a3f3'),
  ('ex_idol', 'roleplay_flavor', 2, '팬과 함께 만드는 앨범 자켓 아이디어는?', ARRAY['앨범자켓','아이디어','팬','디자인']::text[], 'seed_991ce6218993c6a4'),
  ('ex_idol', 'roleplay_flavor', 2, '아이돌 요리 대결에 나간다면 자신작은?', ARRAY['요리','대결','자신작','재미']::text[], 'seed_cc9d5ee0db81bca0'),
  ('ex_idol', 'roleplay_flavor', 2, '콘서트 엔딩 멘트를 지금 쓴다면?', ARRAY['엔딩','멘트','콘서트','감성']::text[], 'seed_14fffffccd65b7b5'),
  ('ex_idol', 'roleplay_flavor', 2, '가상의 유닛 앨범 콘셉트를 만든다면?', ARRAY['유닛','앨범','콘셉트','창작']::text[], 'seed_cd9dcc7a3779e012'),
  ('ex_idol', 'roleplay_flavor', 2, '아이돌 세계관 애니메이션을 만든다면 자기 캐릭터 설정은?', ARRAY['애니','캐릭터','설정','창작']::text[], 'seed_27a523e1c100042a'),
  ('ex_idol', 'roleplay_flavor', 2, '팬과 함께하는 사진전을 연다면 테마와 대표작은?', ARRAY['사진전','테마','팬','예술']::text[], 'seed_c83cc9a5c81f3fb8'),
  ('ex_idol', 'roleplay_flavor', 2, '아이돌 다큐멘터리를 직접 만든다면 어떤 이야기를 담고 싶어?', ARRAY['다큐','이야기','아이돌','진정성']::text[], 'seed_dc00d282a758380b'),
  ('ex_idol', 'roleplay_flavor', 2, '자기 이름을 딴 향수를 만든다면 어떤 향?', ARRAY['향수','이름','디자인','감각']::text[], 'seed_7d5d96875f2aafaf'),
  ('ex_idol', 'roleplay_flavor', 2, '무대 위 퍼포먼스에 특수 효과를 더한다면?', ARRAY['퍼포먼스','특수효과','무대','연출']::text[], 'seed_f36fd2893ea16599'),
  ('ex_idol', 'roleplay_flavor', 2, '아이돌 테마파크를 만든다면 메인 어트랙션은?', ARRAY['테마파크','어트랙션','상상','기획']::text[], 'seed_d6fe6adbbb3e2c54'),
  ('ex_idol', 'roleplay_flavor', 3, '자기의 아이돌 인생을 한 편의 뮤지컬로 만든다면 핵심 넘버와 클라이맥스는?', ARRAY['뮤지컬','넘버','클라이맥스','창작']::text[], 'seed_81c35f9a12ab13cb'),
  ('ex_idol', 'roleplay_flavor', 3, '50년 후 아이돌 문화는 어떤 모습일까? 자기가 상상하는 미래의 아이돌은?', ARRAY['미래','아이돌','문화','상상']::text[], 'seed_304d0c8cf907becf'),
  ('ex_idol', 'roleplay_flavor', 3, '자기의 아이돌 경험을 토대로 소설을 쓴다면 등장인물과 갈등 구조는?', ARRAY['소설','등장인물','갈등','창작']::text[], 'seed_fffb1cf2d1f1085b'),
  ('ex_idol', 'roleplay_flavor', 3, '아이돌 박물관을 만든다면 전시 구성과 하이라이트는?', ARRAY['박물관','전시','아이돌','기획']::text[], 'seed_31953438f7242cb5'),
  ('ex_idol', 'roleplay_flavor', 3, '가상의 마지막 콘서트를 기획한다면 시작부터 끝까지 어떤 흐름?', ARRAY['콘서트','마지막','기획','감성']::text[], 'seed_9559f50e5702e8a4'),
  ('ex_idol', 'roleplay_flavor', 3, '아이돌 아카데미를 설립한다면 교육 철학과 커리큘럼은?', ARRAY['아카데미','교육','철학','비전']::text[], 'seed_3b765095386ccd15'),
  ('ex_idol', 'roleplay_flavor', 3, '자기만의 음악 세계관을 처음부터 끝까지 만들어본다면?', ARRAY['세계관','음악','완성','창작']::text[], 'seed_438c9ced6e614663'),
  ('ex_idol', 'roleplay_flavor', 3, '아이돌과 팬의 관계를 주제로 한 영화 시나리오의 핵심 장면은?', ARRAY['영화','시나리오','팬','관계']::text[], 'seed_7dd0d7b78a27b572'),
  ('ex_idol', 'roleplay_flavor', 3, '100년 후 자기가 만든 음악이 남아있다면 어떤 곡이 남을까?', ARRAY['100년후','음악','유산','상상']::text[], 'seed_1e585b8a7d351a12'),
  ('ex_idol', 'roleplay_flavor', 3, '아이돌 문화 다큐멘터리 시리즈를 만든다면 에피소드 구성은?', ARRAY['다큐','시리즈','에피소드','기획']::text[], 'seed_2521cdff4b9f2657'),
  ('ex_idol', 'roleplay_flavor', 3, '무대 위의 순간을 하나의 미술 작품으로 표현한다면?', ARRAY['미술','작품','무대','예술']::text[], 'seed_e666092b0a0b33ed'),
  ('ex_idol', 'roleplay_flavor', 3, '아이돌 경험을 다음 세대에 전하는 편지 형식의 콘텐츠를 만든다면?', ARRAY['편지','다음세대','전달','가치']::text[], 'seed_730d67910f9ddfa2'),
  ('ex_idol', 'roleplay_flavor', 3, '자기의 아이돌 시대를 타임캡슐에 담는다면 세 가지 아이템과 메시지는?', ARRAY['타임캡슐','아이템','메시지','기념']::text[], 'seed_d20d726982375898'),
  ('ex_idol', 'roleplay_flavor', 3, '아이돌 경험을 바탕으로 한 테드톡 발표를 한다면 주제와 핵심 메시지는?', ARRAY['테드톡','발표','주제','메시지']::text[], 'seed_2a1d9cab510e6a9a'),
  ('ex_idol', 'roleplay_flavor', 3, '자기의 음악과 무대를 하나의 예술 설치 작품으로 재해석한다면?', ARRAY['설치작품','재해석','예술','창의']::text[], 'seed_7cfb0eeffcdad3e6'),
  ('ex_idol', 'deep_but_safe', 1, '요즘 가장 감사한 것 하나는?', ARRAY['감사','긍정','일상']::text[], 'seed_dfb716ad9fa04891'),
  ('ex_idol', 'deep_but_safe', 1, '스트레스 받을 때 하는 일은?', ARRAY['스트레스','해소','방법']::text[], 'seed_ba0353a2c85491f6'),
  ('ex_idol', 'deep_but_safe', 1, '요즘 가장 행복하다고 느끼는 때는?', ARRAY['행복','순간','현재']::text[], 'seed_c1a2d6c902ce64d7'),
  ('ex_idol', 'deep_but_safe', 1, '자기에게 해주고 싶은 칭찬은?', ARRAY['칭찬','자기','긍정']::text[], 'seed_2b3518521e86284b'),
  ('ex_idol', 'deep_but_safe', 1, '좋아하는 명언이 있어?', ARRAY['명언','가치관','인용']::text[], 'seed_b5d9b15c5f29937c'),
  ('ex_idol', 'deep_but_safe', 1, '혼자만의 시간에 뭘 해?', ARRAY['혼자','여가','쉼']::text[], 'seed_f531d185b17fbc71'),
  ('ex_idol', 'deep_but_safe', 1, '요즘 듣고 싶은 말은?', ARRAY['듣고싶은말','감정','소통']::text[], 'seed_348d466c698f0f97'),
  ('ex_idol', 'deep_but_safe', 1, '가장 소중한 물건은?', ARRAY['소중','물건','애착']::text[], 'seed_643b069b69b75b3c'),
  ('ex_idol', 'deep_but_safe', 1, '최근 용기 낸 일은?', ARRAY['용기','도전','경험']::text[], 'seed_2d0bd7bc878e1008'),
  ('ex_idol', 'deep_but_safe', 1, '자기를 단어 하나로 정의한다면?', ARRAY['한단어','자기표현','정체성']::text[], 'seed_ea98e620ac6da9ea'),
  ('ex_idol', 'deep_but_safe', 1, '요즘 가장 많이 하는 생각은?', ARRAY['생각','요즘','내면']::text[], 'seed_d3af70b8cd6a320a'),
  ('ex_idol', 'deep_but_safe', 1, '행복할 때 무의식적으로 하는 건?', ARRAY['행복','습관','무의식']::text[], 'seed_a8c5fa0a3c8e3971'),
  ('ex_idol', 'deep_but_safe', 1, '좋아하는 향기는?', ARRAY['향기','감각','취향']::text[], 'seed_aee970e356022322'),
  ('ex_idol', 'deep_but_safe', 1, '가장 편안한 장소는?', ARRAY['장소','편안','쉼']::text[], 'seed_eb552cb8a6b8a79b'),
  ('ex_idol', 'deep_but_safe', 1, '요즘 보고 있는 작품(책/영화 등)은?', ARRAY['작품','취미','현재']::text[], 'seed_d61eeaebfee4f6bc'),
  ('ex_idol', 'deep_but_safe', 1, '자기한테 맞는 계절은?', ARRAY['계절','성격','취향']::text[], 'seed_d4ce0ece847c6b10'),
  ('ex_idol', 'deep_but_safe', 1, '최근 새로 시도한 건?', ARRAY['시도','새로움','도전']::text[], 'seed_0cfdd542cb098f30'),
  ('ex_idol', 'deep_but_safe', 1, '꽃에 비유하면 자기는?', ARRAY['꽃','비유','자기표현']::text[], 'seed_95a7bf7ebcdf0233'),
  ('ex_idol', 'deep_but_safe', 1, '가장 기대하는 것은?', ARRAY['기대','미래','긍정']::text[], 'seed_a6e11ef9538db7ae'),
  ('ex_idol', 'deep_but_safe', 1, '자기만의 ''작은 사치''는?', ARRAY['사치','행복','취향']::text[], 'seed_ecf2b7e02e7c3a2e'),
  ('ex_idol', 'deep_but_safe', 1, '아이돌 시절의 자기에게 한마디 한다면?', ARRAY['과거','한마디','메시지']::text[], 'seed_756eeb7ff2bd377e'),
  ('ex_idol', 'deep_but_safe', 1, '하루 중 제일 좋아하는 시간대는?', ARRAY['시간대','취향','일상']::text[], 'seed_95a5bc4375656793'),
  ('ex_idol', 'deep_but_safe', 1, '요즘 자기에게 필요한 건?', ARRAY['필요','자기관리','현재']::text[], 'seed_d4c48950f2babb7c'),
  ('ex_idol', 'deep_but_safe', 1, '인생의 BGM을 정한다면?', ARRAY['BGM','인생','음악']::text[], 'seed_c0c9fc38c4689b18'),
  ('ex_idol', 'deep_but_safe', 1, '언제가 가장 자기답다고 느껴?', ARRAY['나다운','시간','정체성']::text[], 'seed_a729d0a55f863f2f'),
  ('ex_idol', 'deep_but_safe', 1, '자기에게 주고 싶은 선물은?', ARRAY['선물','자기','위로']::text[], 'seed_ffd42389590fe452'),
  ('ex_idol', 'deep_but_safe', 1, '힐링 방법은?', ARRAY['힐링','방법','자기관리']::text[], 'seed_7632d22a219ed926'),
  ('ex_idol', 'deep_but_safe', 1, '자기가 대견한 순간은?', ARRAY['대견','성취','긍정']::text[], 'seed_1ce592e8a25ee69c'),
  ('ex_idol', 'deep_but_safe', 1, '마음의 날씨는?', ARRAY['마음','날씨','감정']::text[], 'seed_3420193fd903d5b7'),
  ('ex_idol', 'deep_but_safe', 1, '자주 생각나는 추억은?', ARRAY['추억','기억','과거']::text[], 'seed_8063f2d554df9296'),
  ('ex_idol', 'deep_but_safe', 1, '하루를 한마디로 요약하면?', ARRAY['요약','하루','한마디']::text[], 'seed_88944f485bf2edd2'),
  ('ex_idol', 'deep_but_safe', 1, '좋아하는 자기 장점은?', ARRAY['장점','긍정','자기평가']::text[], 'seed_3859d28d9499a260'),
  ('ex_idol', 'deep_but_safe', 1, '가장 그리운 순간은?', ARRAY['그리움','순간','감성']::text[], 'seed_d7adf918c9a9fa58'),
  ('ex_idol', 'deep_but_safe', 1, '지금 응원하고 싶은 사람은?', ARRAY['응원','사람','관계']::text[], 'seed_2ec10400f279ca48'),
  ('ex_idol', 'deep_but_safe', 1, '무대에서 느꼈던 감정 중 가장 좋았던 건?', ARRAY['감정','무대','기억']::text[], 'seed_e07a5518893270d1'),
  ('ex_idol', 'deep_but_safe', 1, '요즘 감사 인사 하고 싶은 사람은?', ARRAY['감사','사람','관계']::text[], 'seed_f8ae595c0e7335dc'),
  ('ex_idol', 'deep_but_safe', 1, '자기 인생의 키워드 3개는?', ARRAY['키워드','인생','자기표현']::text[], 'seed_ea4e09984f6f5b6d'),
  ('ex_idol', 'deep_but_safe', 1, '최근에 눈물이 났던 이유가 있어? (가볍게)', ARRAY['울음','감정','솔직']::text[], 'seed_a717a3eba6e75af7'),
  ('ex_idol', 'deep_but_safe', 1, '팬에게 가장 전하고 싶은 감정은?', ARRAY['팬','감정','메시지']::text[], 'seed_061c4e66101756db'),
  ('ex_idol', 'deep_but_safe', 1, '오늘 자기에게 점수를 준다면?', ARRAY['점수','자기평가','오늘']::text[], 'seed_b22d89f2b8c6c565'),
  ('ex_idol', 'deep_but_safe', 2, '아이돌 활동 후 자기 정체성을 다시 찾는 과정은 어땠어?', ARRAY['정체성','과정','은퇴후','성장']::text[], 'seed_05b372d44b926c25'),
  ('ex_idol', 'deep_but_safe', 2, '무대 위의 환호와 일상의 고요함, 어떻게 밸런스를 잡아?', ARRAY['밸런스','무대','일상','적응']::text[], 'seed_759a3307db667c67'),
  ('ex_idol', 'deep_but_safe', 2, '팬에게 받은 사랑이 자기 삶에 어떤 영향을 줬어?', ARRAY['팬','사랑','영향','감사']::text[], 'seed_58bac01f61dc0ed9'),
  ('ex_idol', 'deep_but_safe', 2, '아이돌 후의 삶에서 가장 어려웠던 적응 포인트는?', ARRAY['적응','어려움','은퇴후','성장']::text[], 'seed_74fecf4edacb11d2'),
  ('ex_idol', 'deep_but_safe', 2, '''성공''의 정의가 아이돌 전과 후로 어떻게 달라졌어?', ARRAY['성공','정의','변화','가치관']::text[], 'seed_99b6af622169c84b'),
  ('ex_idol', 'deep_but_safe', 2, '가장 힘들었을 때 자기를 지탱해준 건?', ARRAY['힘듦','지탱','극복','감사']::text[], 'seed_d925be243915d741'),
  ('ex_idol', 'deep_but_safe', 2, '아이돌 경험이 ''사랑''에 대한 생각을 어떻게 바꿨어?', ARRAY['사랑','변화','경험','가치관']::text[], 'seed_3bb165f8adc3938a'),
  ('ex_idol', 'deep_but_safe', 2, '지금의 자기에게 가장 큰 도전은?', ARRAY['도전','현재','성장','목표']::text[], 'seed_84b9434e3beed4a5'),
  ('ex_idol', 'deep_but_safe', 2, '팬과의 관계에서 배운 가장 큰 교훈은?', ARRAY['팬','교훈','관계','배움']::text[], 'seed_968eda763a56d15b'),
  ('ex_idol', 'deep_but_safe', 2, '혼자일 때 외로움을 느끼면 어떻게 해?', ARRAY['외로움','대처','방법','자기관리']::text[], 'seed_bf76280ac05b99c4'),
  ('ex_idol', 'deep_but_safe', 2, '아이돌 시절과 지금, 자기가 가장 소중히 여기는 가치의 변화는?', ARRAY['가치','변화','성장','비교']::text[], 'seed_316f23057360da29'),
  ('ex_idol', 'deep_but_safe', 2, '무대를 그리워하는 순간이 있어? 어떤 때?', ARRAY['그리움','무대','순간','감정']::text[], 'seed_ba80c1f44a6d15d4'),
  ('ex_idol', 'deep_but_safe', 2, '자기 인생의 모토를 지금 새로 만든다면?', ARRAY['모토','인생','가치관','현재']::text[], 'seed_f592c646dca7cd90'),
  ('ex_idol', 'deep_but_safe', 2, '힘든 사람에게 용기를 준다면 어떤 말을 해주고 싶어?', ARRAY['용기','응원','메시지','따뜻']::text[], 'seed_9f758012720648f3'),
  ('ex_idol', 'deep_but_safe', 2, '아이돌 이후 새롭게 발견한 자기의 강점은?', ARRAY['강점','발견','성장','자기평가']::text[], 'seed_4386ca5131feaeea'),
  ('ex_idol', 'deep_but_safe', 2, '10년 후의 자기에게 보내는 메시지 한 줄은?', ARRAY['10년후','메시지','미래','감성']::text[], 'seed_d2087aa5c493caf6'),
  ('ex_idol', 'deep_but_safe', 2, '함께 있으면 가장 마음이 편한 사람의 공통점은?', ARRAY['편안','사람','특징','관계']::text[], 'seed_c2d31d40527f16f8'),
  ('ex_idol', 'deep_but_safe', 2, '아이돌 활동에서 가장 큰 후회와 가장 큰 자부심은?', ARRAY['후회','자부심','활동','솔직']::text[], 'seed_043a3f1fee18c082'),
  ('ex_idol', 'deep_but_safe', 2, '꿈에서라도 하고 싶은 일은?', ARRAY['꿈','소원','자유','상상']::text[], 'seed_f3c05114e7fdf987'),
  ('ex_idol', 'deep_but_safe', 2, '''쉼''이란 자기에게 어떤 의미?', ARRAY['쉼','의미','가치관','자기관리']::text[], 'seed_51c0d615a1328c63'),
  ('ex_idol', 'deep_but_safe', 2, '팬들에게 가장 미안한 것과 가장 감사한 것은?', ARRAY['미안','감사','팬','솔직']::text[], 'seed_1072af00104a6d44'),
  ('ex_idol', 'deep_but_safe', 2, '지금 자기가 가장 자신 없는 부분과 극복 노력은?', ARRAY['약점','극복','솔직','성장']::text[], 'seed_f20a41f416e7b34e'),
  ('ex_idol', 'deep_but_safe', 2, '자기가 되고 싶은 ''30대/40대''의 모습은?', ARRAY['미래','이상','자기','가치관']::text[], 'seed_e2f511a9435b5d30'),
  ('ex_idol', 'deep_but_safe', 2, '아이돌 경험이 현재의 인간관계에 어떤 영향을?', ARRAY['인간관계','영향','경험','변화']::text[], 'seed_e699e462bb8953ad'),
  ('ex_idol', 'deep_but_safe', 2, '지금 가장 감사한 팬과의 기억은?', ARRAY['감사','팬','기억','따뜻']::text[], 'seed_ade8102677622437'),
  ('ex_idol', 'deep_but_safe', 3, '아이돌이라는 꿈을 꾸고, 이루고, 지나온 지금, ''꿈''이란 뭐라고 생각해?', ARRAY['꿈','정의','인생','철학']::text[], 'seed_53cbd91e0e9aa093'),
  ('ex_idol', 'deep_but_safe', 3, '무대 위의 함성이 사라진 후, 자기를 지탱하는 가장 큰 힘은?', ARRAY['힘','지탱','은퇴후','가치']::text[], 'seed_00100c9395ff5ea8'),
  ('ex_idol', 'deep_but_safe', 3, '아이돌 경험 전체를 통해 ''나''라는 사람이 어떻게 완성되었다고 느껴?', ARRAY['완성','자기','경험','성장']::text[], 'seed_f795b59b6d756723'),
  ('ex_idol', 'deep_but_safe', 3, '팬과의 관계가 자기 인생에서 어떤 의미를 갖는지 깊이 이야기해줄 수 있어?', ARRAY['팬','의미','관계','깊이']::text[], 'seed_f3bd34e03ff06a1c'),
  ('ex_idol', 'deep_but_safe', 3, '지금까지 살면서 가장 큰 깨달음은?', ARRAY['깨달음','인생','지혜','경험']::text[], 'seed_f39c8a1345ae270e'),
  ('ex_idol', 'deep_but_safe', 3, '자기 인생을 영화로 만든다면 장르와 지금의 장면은?', ARRAY['영화','장르','인생','창의']::text[], 'seed_89599342baa1516e'),
  ('ex_idol', 'deep_but_safe', 3, '세상에 하나만 바꿀 수 있다면?', ARRAY['세상','변화','가치관','소원']::text[], 'seed_2e7ceb52ec8946e3'),
  ('ex_idol', 'deep_but_safe', 3, '자서전의 마지막 장 제목과 첫 문장을 쓴다면?', ARRAY['자서전','마지막장','창의','인생']::text[], 'seed_e9c56840e18c34eb'),
  ('ex_idol', 'deep_but_safe', 3, '''진짜 강한 사람''이란 어떤 사람이라고 생각해?', ARRAY['강함','정의','가치관','철학']::text[], 'seed_1a1576c3a3a05725'),
  ('ex_idol', 'deep_but_safe', 3, '미래에 자기 이야기를 누군가 듣는다면, 어떤 감정을 느꼈으면 좋겠어?', ARRAY['미래','감정','이야기','전달']::text[], 'seed_9a983a6e450e19fe'),
  ('ex_idol', 'deep_but_safe', 3, '''나''라는 사람의 설명서를 쓴다면 핵심 항목은?', ARRAY['설명서','자기','정체성','창의']::text[], 'seed_55acc16db41cde66'),
  ('ex_idol', 'deep_but_safe', 3, '과거의 자기에게 딱 한 가지 충고를 한다면?', ARRAY['과거','충고','지혜','시간']::text[], 'seed_6ed2211bdab268f4'),
  ('ex_idol', 'deep_but_safe', 3, '자기 삶에서 가장 아름다운 순간은?', ARRAY['아름다운','순간','인생','감성']::text[], 'seed_70ea963e6bddd915'),
  ('ex_idol', 'deep_but_safe', 3, '아이돌이었던 과거와 지금의 자기를 모두 안아줄 수 있는 한마디는?', ARRAY['포용','한마디','과거','현재']::text[], 'seed_62a4419d5b6932d8'),
  ('ex_idol', 'deep_but_safe', 3, '100년 후에도 남길 수 있는 자기만의 메시지가 있다면?', ARRAY['100년후','메시지','유산','가치']::text[], 'seed_c715d0bb8689d219')
) AS t(deck_code, subdeck, level, card_text, tags, fingerprint)
WHERE qd.code = t.deck_code
ON CONFLICT (fingerprint) DO UPDATE SET
  card_text = EXCLUDED.card_text,
  tags = EXCLUDED.tags,
  updated_at = now();

-- 통계 확인
DO $$
DECLARE
  v_count INT;
BEGIN
  SELECT COUNT(*) INTO v_count FROM question_cards WHERE fingerprint LIKE 'seed_%';
  RAISE NOTICE 'Imported % question cards', v_count;
END;
$$;
