-- ============================================================
-- 052: Tighten SQL Grants (Least Privilege Principle)
-- ============================================================
-- Replace GRANT ALL with specific privileges on 9 tables.
-- RLS policies already enforce row-level access; this migration
-- removes unnecessary TRUNCATE, REFERENCES, TRIGGER privileges.
-- ============================================================

-- Funding Campaigns: creators create/edit, fans view
REVOKE ALL ON funding_campaigns FROM authenticated;
GRANT SELECT, INSERT, UPDATE ON funding_campaigns TO authenticated;

-- Reward Tiers: creators full CRUD
REVOKE ALL ON funding_reward_tiers FROM authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON funding_reward_tiers TO authenticated;

-- Pledges: fans create pledges, both view
REVOKE ALL ON funding_pledges FROM authenticated;
GRANT SELECT, INSERT ON funding_pledges TO authenticated;

-- FAQ Items: creators full CRUD
REVOKE ALL ON funding_faq_items FROM authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON funding_faq_items TO authenticated;

-- Updates: creators post/edit, fans view
REVOKE ALL ON funding_updates FROM authenticated;
GRANT SELECT, INSERT, UPDATE ON funding_updates TO authenticated;

-- Prelaunch Signups: fans sign up, both view
REVOKE ALL ON funding_prelaunch_signups FROM authenticated;
GRANT SELECT, INSERT ON funding_prelaunch_signups TO authenticated;

-- Payments: records created via Edge Functions, users view
REVOKE ALL ON funding_payments FROM authenticated;
GRANT SELECT, INSERT ON funding_payments TO authenticated;

-- Settlement Statements: read-only (generated by Edge Functions with service_role)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'settlement_statements') THEN
    REVOKE ALL ON settlement_statements FROM authenticated;
    GRANT SELECT ON settlement_statements TO authenticated;
  ELSE
    RAISE NOTICE 'settlement_statements table does not exist, skipping grant changes';
  END IF;
END $$;

-- Refund Queue: requests created, processed server-side
REVOKE ALL ON funding_refund_queue FROM authenticated;
GRANT SELECT, INSERT ON funding_refund_queue TO authenticated;
